// apps/desktop/src/components/common/MarkdownRenderer.tsx
import { useState, useCallback, useEffect, useRef } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import rehypeRaw from "rehype-raw";
import "katex/dist/katex.min.css";
import { open } from "@tauri-apps/plugin-shell";
import { Check, Copy } from "lucide-react";
import { readDocumentImage } from "../../services/tauriBridge";

// ── Math inside HTML (e.g. <td>$x$</td>) ──
function rehypeMathInHtml() {
  return (tree: any) => {
    const walk = (nodes: any[], parent?: any) => {
      if (!nodes) return;
      for (let i = 0; i < nodes.length; i++) {
        const node = nodes[i];
        if (node.type === "element") { walk(node.children, node); }
        else if (node.type === "text" && parent) {
          const text = node.value || "";
          const mr = /\$\$([\s\S]*?)\$\$|\$([^$\n]+?)\$/g;
          let m; let last = 0; const reps: any[] = [];
          while ((m = mr.exec(text)) !== null) {
            if (m.index > last) reps.push({ type: "text", value: text.slice(last, m.index) });
            const isDisp = m[0].startsWith("$$");
            reps.push({ type: "element", tagName: "span",
              properties: { className: isDisp ? ["math", "math-display"] : ["math", "math-inline"] },
              children: [{ type: "text", value: isDisp ? m[1] : m[2] }] });
            last = mr.lastIndex;
          }
          if (reps.length > 0) {
            if (last < text.length) reps.push({ type: "text", value: text.slice(last) });
            nodes.splice(i, 1, ...reps); i += reps.length - 1;
          }
        }
      }
    };
    walk(tree.children);
  };
}

// ── [N] → clickable source badge ──
function embedBadges(content: string, sourceCount: number): string {
  if (!sourceCount) return content;
  const segments = content.split(/(```[\s\S]*?```|`[^`\n]+`|\$\$[\s\S]*?\$\$|\$[^$\n]+\$)/g);
  return segments.map((seg, i) => {
    if (i % 2 === 1) return seg;
    // Match [3-5] (range) or [3] (single)
    return seg.replace(/\[(\d+)(?:[-–](\d+))?\]/g, (m, n1, n2) => {
      const start = parseInt(n1) - 1;
      const end = n2 ? parseInt(n2) - 1 : start;
      if (start < 0 || end >= sourceCount || start > end) return m;
      if (start === end) {
        return `<sup data-source="${start}" class="skb-badge">${n1}</sup>`;
      }
      return `<sup data-source-start="${start}" data-source-end="${end}" class="skb-badge">${n1}-${n2}</sup>`;
    });
  }).join("");
}

/** Merge multiple sources into a single preview object */
function mergeSources(list: any[]): any {
  if (list.length === 1) return list[0];
  return {
    ...list[0],
    chunk_id: list.map(s => s.chunk_id).join("+"),
    content: list.map((s, i) =>
      `> 📄 **Chunk #${s.metadata?.chunk_index ?? (i + 1)}**\n\n${s.content}`
    ).join("\n\n---\n\n"),
    metadata: { ...list[0].metadata, _merged: true, _count: list.length, _range: `${list[0].metadata?.chunk_index ?? "?"}-${list[list.length-1].metadata?.chunk_index ?? "?"}` },
  };
}

interface Props {
  children: string;
  className?: string;
  sources?: any[];
  onSourceClick?: (source: any) => void;
  imgKbId?: string;
  imgDocId?: string;
}

function CodeBlock({ children, className }: { children: React.ReactNode; className?: string }) {
  const [copied, setCopied] = useState(false);
  const text = typeof children === "string" ? children : String(children ?? "");
  return (
    <div className="relative group/code">
      <button onClick={async () => { await navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000); }}
        className="absolute top-2 right-2 p-1.5 rounded-md bg-background/80 border opacity-0 group-hover/code:opacity-100 transition-opacity z-10" title="Copy code">
        {copied ? <Check className="w-3.5 h-3.5 text-green-500" /> : <Copy className="w-3.5 h-3.5 text-muted-foreground" />}
      </button>
      <pre className={className}>{children}</pre>
    </div>
  );
}

// Per-render image cache: filename → data URL
const _imgCache = new Map<string, string>();

function InlineImg({ src, alt, imgKbId, imgDocId }: { src?: string; alt?: string; imgKbId?: string; imgDocId?: string }) {
  const [dataUrl, setDataUrl] = useState(() => _imgCache.get(src || "") || "");
  const pendingRef = useRef(false);

  useEffect(() => {
    if (!src || !imgKbId || !imgDocId) return;
    if (dataUrl || pendingRef.current) return;
    // Only intercept relative image paths (from MinerU markdown)
    const name = src.replace(/\\/g, "/").split("/").pop() || src;
    if (name === src && !src.startsWith("images/")) return; // not a doc image
    pendingRef.current = true;
    (async () => {
      try {
        const bytes = await readDocumentImage(imgKbId!, imgDocId!, name);
        const blob = new Blob([new Uint8Array(bytes)]);
        const url = URL.createObjectURL(blob);
        _imgCache.set(src, url);
        setDataUrl(url);
      } catch {
        // Image not found in doc — fall back to original src
      }
    })();
  }, [src, imgKbId, imgDocId, dataUrl]);

  return <img src={dataUrl || src} alt={alt || ""} className="max-w-full h-auto rounded-lg my-2" loading="lazy" />;
}

export function MarkdownRenderer({ children, className, sources, onSourceClick, imgKbId, imgDocId }: Props) {
  const count = sources?.length || 0;
  const content = count ? embedBadges(children, count) : children;

  const onClick = useCallback((e: React.MouseEvent) => {
    if (!onSourceClick || !sources) return;
    const el = (e.target as HTMLElement).closest("[data-source], [data-source-start]") as HTMLElement | null;
    if (!el) return;
    const s = el.getAttribute("data-source-start");
    if (s != null) {
      // Range badge [3-5]
      const start = parseInt(s);
      const end = parseInt(el.getAttribute("data-source-end") || s);
      if (start >= 0 && end < sources.length) {
        onSourceClick(mergeSources(sources.slice(start, end + 1)));
      }
    } else {
      // Single badge [3]
      const idx = parseInt(el.getAttribute("data-source") || "-1");
      if (idx >= 0 && idx < sources.length) onSourceClick(sources[idx]);
    }
  }, [onSourceClick, sources]);

  return (
    <div className={className} onClick={onClick}>
      <style>{`
        .skb-badge{display:inline-flex;align-items:center;justify-content:center;
          min-width:18px;height:18px;border-radius:50%;
          background:rgba(79,70,229,0.12);color:#4f46e5;
          font-size:10px;font-weight:600;text-decoration:none;
          cursor:pointer;vertical-align:super;margin:0 2px;line-height:1}
        .skb-badge:hover{background:rgba(79,70,229,0.24)}
        .dark .skb-badge{background:rgba(129,140,248,0.15);color:#a5b4fc}
        .dark .skb-badge:hover{background:rgba(129,140,248,0.28)}
      `}</style>
      <ReactMarkdown
        remarkPlugins={[remarkGfm, remarkMath]}
        rehypePlugins={[rehypeRaw, rehypeMathInHtml, [rehypeKatex, { strict: false, throwOnError: false }]]}
        components={{
          img({ src, alt }: any) {
            return <InlineImg src={src} alt={alt} imgKbId={imgKbId} imgDocId={imgDocId} />;
          },
          a({ href, children: aChildren, ...props }) {
            if (href && /^https?:\/\//.test(href)) {
              return <a href={href} onClick={e => { e.preventDefault(); open(href!); }}
                target="_blank" rel="noopener noreferrer" className="text-primary underline cursor-pointer" {...props}>{aChildren}</a>;
            }
            return <a href={href} {...props}>{aChildren}</a>;
          },
          sup({ children: sChildren, ...props }) {
            return <sup {...props}>{sChildren}</sup>;
          },
          pre({ children: pChildren, ...props }) {
            const code = (pChildren as any)?.props;
            return <CodeBlock className={code?.className}>{code?.children || pChildren}</CodeBlock>;
          },
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
}

// apps/desktop/src/components/common/MarkdownRenderer.vue
<script setup lang="ts">
import { computed, inject, onMounted, watch } from "vue";
import MarkdownIt from "markdown-it";
import katex from "katex";
import "katex/dist/katex.min.css";
import { latexNormalize } from "@/utils/latexNormalize";
import { imageVersion, getImageUrl, ensureImagesLoaded } from "@/utils/resolveImages";

const props = defineProps<{
  content: string;
  sources?: any[];
  theme?: string;
  /** Override KB/docs to search for images when sources aren't available */
  imgKbId?: string;
  imgDocId?: string;
}>();

const emit = defineEmits<{
  sourceClick: [source: any];
}>();

const injectedTheme = inject("markdownTheme", "academic");

const md = new MarkdownIt({
  html: true,
  breaks: true,
  linkify: true,
});

// Inline math: $...$ (runs before emphasis so _ inside math is not treated as italic)
md.inline.ruler.before("emphasis", "inline_math", (state, silent) => {
  const pos = state.pos;
  if (state.src[pos] !== "$") return false;
  const end = state.src.indexOf("$", pos + 1);
  if (end === -1) return false;
  if (state.src[pos + 1] === "$") return false; // skip $$
  if (!silent) {
    const token = state.push("inline_math", "math", 0);
    token.content = state.src.slice(pos + 1, end);
    token.markup = "$";
  }
  state.pos = end + 1;
  return true;
});

// Display math: $$...$$ (before paragraph to capture $$ blocks)
md.block.ruler.before("paragraph", "display_math", (state, startLine, endLine, silent) => {
  const startPos = state.bMarks[startLine] + state.tShift[startLine];
  if (state.src.slice(startPos, startPos + 2) !== "$$") return false;
  const end = state.src.indexOf("$$", startPos + 2);
  if (end === -1) return false;
  const content = state.src.slice(startPos + 2, end);
  if (!silent) {
    const token = state.push("display_math", "math", 0);
    token.content = content.trim();
    token.markup = "$$";
    token.block = true;
  }
  const newLine = startLine + state.src.slice(state.bMarks[startLine], end).split("\n").length - 1;
  state.line = newLine + 1;
  return true;
});

// Render math tokens
md.renderer.rules["inline_math"] = function (tokens, idx) {
  let content = tokens[idx].content.replace(/([_^])\s+(?=\{)/g, '$1');
  content = content.replace(/\\left\s*\{/g, '\\left\\{').replace(/\\right\s*\}/g, '\\right\\}');
  try { return katex.renderToString(content, { throwOnError: false, strict: false }); }
  catch { return `$${tokens[idx].content}$`; }
};
md.renderer.rules["display_math"] = function (tokens, idx) {
  let content = tokens[idx].content.replace(/([_^])\s+(?=\{)/g, '$1');
  content = content.replace(/\\left\s*\{/g, '\\left\\{').replace(/\\right\s*\}/g, '\\right\\}');
  try { return katex.renderToString(content, { displayMode: true, throwOnError: false, strict: false }); }
  catch { return `$$\n${tokens[idx].content}\n$$`; }
};

// Helper: render $...$ math inside HTML element content
function renderInlineMathInHtml(inner: string): string {
  if (inner.includes('class="katex"') || inner.includes('class="katex-display"')) return inner;
  return inner.replace(/\$([^$]+?)\$/g, (_m: string, math: string) => {
    let content = math.replace(/([_^])\s+(?=\{)/g, '$1');
    content = content.replace(/\\left\s*\{/g, '\\left\\{').replace(/\\right\s*\}/g, '\\right\\}');
    try { return katex.renderToString(content, { throwOnError: false, strict: false }); }
    catch { return `$${math}$`; }
  });
}

const renderedHtml = computed(() => {
  // Access imageVersion reactively — triggers re-render when images finish loading
  void imageVersion.value;
  // Normalize LaTeX delimiters, wrap bare environments, fix \tag, etc.
  const processedContent = latexNormalize(props.content);

  let html = md.render(processedContent);

  // Replace image src with resolved object URLs
  html = html.replace(
    /src="([^"]+)"/gi,
    (_m: string, src: string) => {
      const fn = src.replace(/\\/g, "/").split("/").pop()!;
      const url = getImageUrl(fn);
      if (url) {
        return `src="${url}"`;
      }
      return _m;
    }
  );

  // Post-process: render $...$ inside HTML elements (e.g. <td> in tables)
  // that markdown-it skipped because html:true treats HTML content as literal.
  // Only replace $...$ that are NOT already inside katex spans.
  html = html.replace(/(<td[^>]*>)([\s\S]*?)(<\/td>)/gi, (_m: string, open: string, inner: string, close: string) => {
    return open + renderInlineMathInHtml(inner) + close;
  });
  html = html.replace(/(<th[^>]*>)([\s\S]*?)(<\/th>)/gi, (_m: string, open: string, inner: string, close: string) => {
    return open + renderInlineMathInHtml(inner) + close;
  });
  html = html.replace(/(<figcaption[^>]*>)([\s\S]*?)(<\/figcaption>)/gi, (_m: string, open: string, inner: string, close: string) => {
    return open + renderInlineMathInHtml(inner) + close;
  });

  // Replace [N] or [N-M] with clickable source badges
  if (props.sources?.length) {
    html = html.replace(
      /\[(\d+)(?:[-–](\d+))?\]/g,
      (match: string, n1: string, n2?: string) => {
        const start = parseInt(n1, 10) - 1;
        const end = n2 ? parseInt(n2, 10) - 1 : start;
        if (
          start < 0 ||
          end >= (props.sources?.length ?? 0) ||
          start > end
        ) {
          return match;
        }
        if (start === end) {
          return `<sup data-source="${start}" class="skb-badge">${n1}</sup>`;
        }
        return `<sup data-source-start="${start}" data-source-end="${end}" class="skb-badge">${n1}-${n2}</sup>`;
      }
    );
  }

  return html;
});

// Trigger image loading
function getCandidates() {
  const list: { kb_id: string; doc_id: string }[] = [];
  if (props.imgKbId && props.imgDocId) {
    list.push({ kb_id: props.imgKbId, doc_id: props.imgDocId });
  }
  for (const s of props.sources || []) {
    if (s.kb_id && s.doc_id) {
      list.push({ kb_id: s.kb_id, doc_id: s.doc_id });
    }
  }
  return list;
}
onMounted(() => ensureImagesLoaded(props.content, getCandidates()));
watch(() => props.content, () => ensureImagesLoaded(props.content, getCandidates()));

function onContentClick(e: MouseEvent) {
  // Open external links in default browser
  const link = (e.target as HTMLElement).closest("a") as HTMLAnchorElement | null;
  if (link && link.href && !link.href.startsWith("http://localhost") && !link.href.startsWith(window.location.origin)) {
    e.preventDefault();
    e.stopPropagation();
    import("@tauri-apps/plugin-shell").then(({ open }) => open(link.href).catch(() => window.open(link.href, "_blank")));
    return;
  }
  onBadgeClick(e);
}

function onBadgeClick(e: MouseEvent) {
  const el = (e.target as HTMLElement).closest(
    "[data-source], [data-source-start]"
  ) as HTMLElement | null;
  if (!el || !props.sources) return;

  const start = parseInt(
    el.getAttribute("data-source-start") ||
      el.getAttribute("data-source") ||
      "-1",
    10
  );
  const end = parseInt(el.getAttribute("data-source-end") || String(start), 10);

  if (start >= 0 && end < props.sources.length) {
    emit("sourceClick", props.sources.slice(start, end + 1));
  }
}
</script>

<template>
  <div
    class="markdown-renderer prose prose-sm max-w-none dark:prose-invert"
    :class="'md-theme-' + injectedTheme"
    @click="onContentClick"
    v-html="renderedHtml"
  />
</template>

<style scoped>
.markdown-renderer {
  line-height: 1.7;
  word-wrap: break-word;
}

.markdown-renderer :deep(p) {
  margin: 0.5em 0;
}

.markdown-renderer :deep(pre) {
  background: var(--surface-raised);
  border: 1px solid var(--border-color);
  border-radius: 6px;
  padding: 12px 16px;
  overflow-x: auto;
}

.markdown-renderer :deep(code) {
  font-family: "SF Mono", "Fira Code", "Consolas", monospace;
  font-size: 0.875em;
  color: var(--text-primary, inherit);
}

.markdown-renderer :deep(pre code) {
  background: none;
  padding: 0;
}

.markdown-renderer :deep(img) {
  max-width: 100%;
  border-radius: 6px;
}

.markdown-renderer :deep(a) {
  color: var(--accent-color);
  text-decoration: none;
}

.markdown-renderer :deep(a:hover) {
  text-decoration: underline;
}

.markdown-renderer :deep(table) {
  width: 100%;
  border-collapse: collapse;
}

.markdown-renderer :deep(th),
.markdown-renderer :deep(td) {
  padding: 6px 10px;
  border: 1px solid var(--border-color);
  text-align: left;
}

.markdown-renderer :deep(th) {
  background: var(--surface-raised);
  font-weight: 600;
}

.markdown-renderer :deep(blockquote) {
  border-left: 3px solid var(--accent-color);
  margin: 0.5em 0;
  padding: 4px 12px;
  color: var(--text-secondary);
  background: var(--accent-muted);
  border-radius: 0 4px 4px 0;
}

.markdown-renderer :deep(ul),
.markdown-renderer :deep(ol) {
  padding-left: 1.5em;
}

.markdown-renderer :deep(h1),
.markdown-renderer :deep(h2),
.markdown-renderer :deep(h3),
.markdown-renderer :deep(h4) {
  color: var(--text-primary);
  font-weight: 600;
  margin: 1em 0 0.5em;
}

.markdown-renderer :deep(h1) { font-size: 1.5em; }
.markdown-renderer :deep(h2) { font-size: 1.25em; }
.markdown-renderer :deep(h3) { font-size: 1.1em; }
</style>

<style>
@import "@/styles/academic.css";
@import "@/styles/github.css";
</style>
