// apps/desktop/src/components/documents/DocumentManager.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from "vue";
import { useRouter } from "vue-router";
import { Plus, Trash2, RefreshCw, Eye, FileText, FolderOpen } from "lucide-vue-next";
import { useKBStore } from "@/stores/kbStore";
import { ElMessage, ElMessageBox } from "element-plus";
import type { Document } from "@/types";

const props = defineProps<{
  kbId: string;
}>();

const router = useRouter();
const store = useKBStore();

const selectedDoc = ref<Document | null>(null);
const uploadLoading = ref(false);

const documents = computed(() => store.documents);
const indexingProgress = computed(() => store.indexingProgress);

onMounted(() => {
  if (props.kbId) {
    store.loadDocuments(props.kbId);
  }
});

watch(
  () => props.kbId,
  (newId) => {
    if (newId) {
      store.loadDocuments(newId);
    }
  }
);

function getStatusType(status: string): string {
  switch (status) {
    case "done":
      return "success";
    case "parsing":
    case "pending":
      return "warning";
    case "failed":
      return "danger";
    default:
      return "info";
  }
}

function getProgress(doc: Document): { percent: number; stage: string } | null {
  return indexingProgress.value[doc.id] ?? null;
}

async function handleUpload() {
  let filePath: string | null = null;
  try {
    const { open } = await import("@tauri-apps/plugin-dialog");
    filePath = await open({
      multiple: false,
      filters: [
        {
          name: "Documents",
          extensions: [
            "pdf", "docx", "pptx", "xlsx", "md", "txt",
            "html", "htm", "csv", "json", "xml", "epub",
            "png", "jpg", "jpeg",
          ],
        },
      ],
    });
  } catch {
    filePath = prompt("Enter the full file path:") ?? null;
  }
  if (!filePath) return;

  uploadLoading.value = true;
  try {
    await store.uploadDocument(props.kbId, filePath);
    ElMessage.success("Document uploaded and processing started");
  } catch (e) {
    ElMessage.error(String(e));
  } finally {
    uploadLoading.value = false;
  }
}

async function handleDelete(doc: Document) {
  try {
    await ElMessageBox.confirm(
      `Delete "${doc.name}"? This action cannot be undone.`,
      "Delete Document",
      { confirmButtonText: "Delete", cancelButtonText: "Cancel", type: "warning" }
    );
    await store.deleteDocument(props.kbId, doc.id);
    ElMessage.success("Document deleted");
  } catch {
    // cancelled
  }
}

function handleView(doc: Document) {
  // Open the document preview in a new tab or navigate
  const url = router.resolve({
    name: "document-preview",
    params: { kbId: props.kbId, docId: doc.id },
  });
  window.open(url.href, "_blank");
}

async function handleReindex(doc: Document) {
  try {
    await store.reindexDocument(props.kbId, doc.id, doc.name);
    ElMessage.success("Re-index started");
  } catch (e) {
    ElMessage.error(String(e));
  }
}

function navigateToView(doc: Document) {
  router.push({
    name: "document-preview",
    params: { kbId: props.kbId, docId: doc.id },
  });
}
</script>

<template>
  <div class="document-manager">
    <!-- Toolbar -->
    <div class="doc-toolbar">
      <span class="doc-count" v-if="documents.length">
        {{ documents.length }} document{{ documents.length !== 1 ? "s" : "" }}
      </span>
      <el-button size="small" type="primary" :loading="uploadLoading" @click="handleUpload">
        <Plus :size="14" style="margin-right: 4px" />
        Upload
      </el-button>
    </div>

    <!-- Loading -->
    <div v-if="store.loading && documents.length === 0" class="loading-state">
      <div class="loading-spinner" />
      <p>Loading documents...</p>
    </div>

    <!-- Empty -->
    <div v-else-if="documents.length === 0" class="empty-state">
      <FolderOpen :size="40" class="empty-icon" />
      <p class="empty-title">No documents yet</p>
      <p class="empty-hint">Upload a PDF, DOCX, or other document to get started</p>
    </div>

    <!-- Table -->
    <el-table
      v-else
      :data="documents"
      style="width: 100%"
      size="small"
      stripe
      highlight-current-row
      @row-click="navigateToView"
    >
      <el-table-column label="Name" min-width="200">
        <template #default="{ row }: { row: Document }">
          <div class="doc-name-cell">
            <FileText :size="14" class="doc-type-icon" />
            <span class="doc-name-text">{{ row.name }}</span>
          </div>
        </template>
      </el-table-column>

      <el-table-column label="Type" width="80" align="center">
        <template #default="{ row }: { row: Document }">
          <span class="doc-type">{{ row.file_type?.toUpperCase() || "--" }}</span>
        </template>
      </el-table-column>

      <el-table-column label="Status" width="110" align="center">
        <template #default="{ row }: { row: Document }">
          <div class="status-cell">
            <el-tag :type="getStatusType(row.parse_status)" size="small" effect="plain">
              {{ row.parse_status }}
            </el-tag>
            <div
              v-if="getProgress(row)"
              class="index-progress"
              :title="`${getProgress(row)!.stage}: ${getProgress(row)!.percent.toFixed(0)}%`"
            >
              <el-progress
                :percentage="Math.round(getProgress(row)!.percent)"
                :stroke-width="4"
                size="small"
              />
            </div>
          </div>
        </template>
      </el-table-column>

      <el-table-column label="Chunks" width="80" align="center">
        <template #default="{ row }: { row: Document }">
          <span class="chunk-count">{{ row.chunk_count }}</span>
        </template>
      </el-table-column>

      <el-table-column label="Actions" width="180" align="center" fixed="right">
        <template #default="{ row }: { row: Document }">
          <div class="action-btns">
            <el-tooltip content="View document" placement="top">
              <el-button size="small" circle @click.stop="handleView(row)">
                <Eye :size="14" />
              </el-button>
            </el-tooltip>
            <el-tooltip content="Re-index" placement="top">
              <el-button
                size="small"
                circle
                :loading="!!getProgress(row)"
                @click.stop="handleReindex(row)"
              >
                <RefreshCw :size="14" />
              </el-button>
            </el-tooltip>
            <el-tooltip content="Delete" placement="top">
              <el-button size="small" circle type="danger" @click.stop="handleDelete(row)">
                <Trash2 :size="14" />
              </el-button>
            </el-tooltip>
          </div>
        </template>
      </el-table-column>
    </el-table>
  </div>
</template>

<style scoped>
.document-manager {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.doc-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.doc-count {
  font-size: 13px;
  color: var(--text-secondary);
}

.doc-name-cell {
  display: flex;
  align-items: center;
  gap: 8px;
}

.doc-type-icon {
  color: var(--accent-color);
  flex-shrink: 0;
}

.doc-name-text {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.doc-type {
  font-size: 11px;
  font-family: "SF Mono", "Fira Code", monospace;
  color: var(--text-secondary);
}

.status-cell {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
}

.chunk-count {
  font-size: 13px;
  font-weight: 500;
  color: var(--text-primary);
}

.action-btns {
  display: flex;
  gap: 4px;
  justify-content: center;
}

.index-progress {
  width: 80px;
}

.loading-state,
.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 60px 24px;
  text-align: center;
  gap: 8px;
}

.loading-spinner {
  width: 20px;
  height: 20px;
  border: 2px solid var(--border-color);
  border-top-color: var(--accent-color);
  border-radius: 50%;
  animation: spin 0.6s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.empty-icon {
  color: var(--border-color);
}

.empty-title {
  font-size: 15px;
  font-weight: 500;
  color: var(--text-primary);
  margin: 0;
}

.empty-hint {
  font-size: 13px;
  color: var(--text-secondary);
  margin: 0;
}

:deep(.el-table) {
  --el-table-header-bg-color: var(--surface-raised);
  --el-table-tr-bg-color: transparent;
  --el-table-border-color: var(--border-color);
  --el-table-text-color: var(--text-primary);
  --el-table-header-text-color: var(--text-secondary);
}

:deep(.el-table__row) {
  cursor: pointer;
}
</style>

// apps/desktop/src/components/documents/DocumentManager.tsx
import { useEffect, useState, useCallback } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useKBStore } from "../../stores/useKBStore";
import { useI18n } from "../../i18n";
import { indexDocument } from "../../services/pythonClient";
import { Upload, FileText, Trash2, Loader2, CheckCircle, XCircle, Clock, Eye } from "lucide-react";
import type { Document } from "../../types";

const STATUS_MAP: Record<string, { icon: React.ReactNode; labelKey: "parse.pending" | "parse.parsing" | "parse.done" | "parse.failed" }> = {
  pending: { icon: <Clock className="w-4 h-4 text-yellow-500" />, labelKey: "parse.pending" },
  parsing: { icon: <Loader2 className="w-4 h-4 text-blue-500 animate-spin" />, labelKey: "parse.parsing" },
  done: { icon: <CheckCircle className="w-4 h-4 text-green-500" />, labelKey: "parse.done" },
  failed: { icon: <XCircle className="w-4 h-4 text-red-500" />, labelKey: "parse.failed" },
};

export function DocumentManager() {
  const { kbId } = useParams<{ kbId: string }>();
  const navigate = useNavigate();
  const { t } = useI18n();
  const { documents, loadDocuments, uploadDocument, deleteDocument, refreshDocument } = useKBStore();
  const [uploading, setUploading] = useState(false);
  const [indexing, setIndexing] = useState<Record<string, boolean>>({});

  useEffect(() => { if (kbId) loadDocuments(kbId); }, [kbId]);

  useEffect(() => {
    const interval = setInterval(() => {
      documents.filter((d) => d.parse_status === "parsing").forEach((d) => {
        if (kbId) refreshDocument(kbId, d.id);
      });
    }, 3000);
    return () => clearInterval(interval);
  }, [documents, kbId]);

  const handleUpload = useCallback(async () => {
    if (!kbId) return;
    try {
      const { open } = await import("@tauri-apps/plugin-dialog");
      const selected = await open({
        multiple: false,
        filters: [{ name: t("docs.uploadFilter"), extensions: ["pdf","doc","docx","ppt","pptx","xls","xlsx","png","jpg","jpeg","webp","gif","bmp","html","md","markdown","txt","zip"] }],
      });
      if (selected) {
        setUploading(true);
        await uploadDocument(kbId, selected as string);
        if (kbId) await loadDocuments(kbId);
        setUploading(false);
      }
    } catch (e) { console.error(e); setUploading(false); }
  }, [kbId, uploadDocument, loadDocuments, t]);

  const handleDelete = async (docId: string) => { if (kbId) await deleteDocument(kbId, docId); };

  const handleIndex = async (doc: Document) => {
    if (!kbId) return;
    try {
      setIndexing((p) => ({ ...p, [doc.id]: true }));
      const { getDocumentContent } = await import("../../services/tauriBridge");
      const content = await getDocumentContent(kbId, doc.id);
      await indexDocument({ kb_id: kbId, doc_id: doc.id, doc_name: doc.name, markdown_content: content.markdown });
      setIndexing((p) => ({ ...p, [doc.id]: false }));
    } catch (e) { console.error(e); setIndexing((p) => ({ ...p, [doc.id]: false })); }
  };

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold">{t("docs.title")}</h2>
          <p className="text-muted-foreground text-sm mt-1">{t("docs.desc")}</p>
        </div>
        <button onClick={handleUpload} disabled={uploading}
          className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:opacity-90 disabled:opacity-50">
          {uploading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Upload className="w-4 h-4" />}
          {t("docs.upload")}
        </button>
      </div>

      {documents.length === 0 ? (
        <div className="text-center py-16">
          <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-3" />
          <p className="text-muted-foreground text-lg">{t("docs.empty")}</p>
          <p className="text-muted-foreground text-sm mt-1">{t("docs.emptyHint")}</p>
        </div>
      ) : (
        <div className="space-y-2">
          {documents.map((doc) => {
            const status = STATUS_MAP[doc.parse_status] || STATUS_MAP.pending;
            return (
              <div key={doc.id} className="flex items-center justify-between p-3 border rounded-lg bg-card">
                <div className="flex items-center gap-3 flex-1 min-w-0">
                  <FileText className="w-5 h-5 text-primary shrink-0" />
                  <div className="min-w-0">
                    <p className="font-medium text-sm truncate">{doc.name}</p>
                    <p className="text-xs text-muted-foreground">
                      {(doc.file_size / 1024).toFixed(1)} KB &bull; {doc.file_type.toUpperCase()} &bull; {doc.chunk_count} {t("kb.chunks")}
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-2 ml-4">
                  <span className="flex items-center gap-1 text-xs text-muted-foreground">
                    {status.icon}{t(status.labelKey)}
                  </span>
                  {doc.parse_status === "done" && (
                    <button onClick={() => handleIndex(doc)} disabled={indexing[doc.id]}
                      className="px-2 py-1 bg-blue-500 text-white rounded text-xs font-medium hover:bg-blue-600 disabled:opacity-50">
                      {indexing[doc.id] ? t("docs.indexing") : t("docs.index")}
                    </button>
                  )}
                  <button onClick={() => navigate(`/kb/${kbId}/documents/${doc.id}`)}
                    className="p-1.5 hover:bg-muted rounded-md" title={t("docs.preview")}><Eye className="w-4 h-4" /></button>
                  <button onClick={() => handleDelete(doc.id)}
                    className="p-1.5 hover:bg-red-50 rounded-md text-muted-foreground hover:text-red-500" title={t("docs.delete")}><Trash2 className="w-4 h-4" /></button>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
