// apps/desktop/src/components/knowledge-base/KBDashboard.tsx
import { useEffect, useState, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { useKBStore, type SortMode } from "../../stores/useKBStore";
import { useI18n } from "../../i18n";
import { Plus, Trash2, FolderOpen, BookOpen, FileText, Layers, Pin, PinOff, Grid3X3, AlignJustify, LayoutGrid, RefreshCw, Search } from "lucide-react";
import { ConfirmDialog } from "../common/ConfirmDialog";
import type { KnowledgeBase } from "../../types";
import { GlobalSearchDialog } from "../search/GlobalSearchDialog";

function useSortOptions() {
  const { t } = useI18n();
  return [
    { value: "manual" as SortMode, label: t("kb.sortDefault") },
    { value: "name-asc" as SortMode, label: t("kb.sortNameAsc") },
    { value: "name-desc" as SortMode, label: t("kb.sortNameDesc") },
    { value: "date-asc" as SortMode, label: t("kb.sortDateAsc") },
    { value: "date-desc" as SortMode, label: t("kb.sortDateDesc") },
  ];
}

export function KBDashboard() {
  const navigate = useNavigate();
  const { t } = useI18n();
  const { knowledgeBases, loadKBs, createKB, deleteKB, togglePinKB, viewMode, sortMode, setViewMode, setSortMode, getSortedKBs } = useKBStore();
  const [showCreate, setShowCreate] = useState(false);
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [deleteTarget, setDeleteTarget] = useState<string | null>(null);
  const [globalSearchOpen, setGlobalSearchOpen] = useState(false);

  useEffect(() => { loadKBs(); }, []);

  const sortedKBs = useMemo(() => getSortedKBs(), [knowledgeBases, sortMode]);
  const sortOptions = useSortOptions();

  const handleCreate = async () => {
    if (!name.trim()) return;
    await createKB(name, description);
    setName(""); setDescription(""); setShowCreate(false);
  };

  const handleDelete = (kbId: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setDeleteTarget(kbId);
  };

  const handleDeleteConfirm = async () => {
    if (deleteTarget) {
      await deleteKB(deleteTarget);
      setDeleteTarget(null);
    }
  };

  const handleRefresh = async () => { await loadKBs(); };

  const handlePin = async (kbId: string, e: React.MouseEvent) => {
    e.stopPropagation();
    await togglePinKB(kbId);
  };

  const renderCompactItem = (kb: KnowledgeBase) => (
    <div key={kb.id} onClick={() => navigate(`/kb/${kb.id}`)}
      className="flex items-center justify-between px-3 py-1.5 border rounded-md bg-card hover:border-primary/50 cursor-pointer transition-colors">
      <div className="flex items-center gap-1.5 min-w-0 flex-1">
        {kb.pinned && <Pin className="w-3 h-3 text-amber-500 shrink-0" />}
        {!kb.pinned && <FolderOpen className="w-3.5 h-3.5 text-primary/70 shrink-0" />}
        <span className="font-medium text-sm truncate">{kb.name}</span>
        {kb.description && (
          <span className="text-xs text-muted-foreground truncate max-w-[12rem] hidden sm:inline shrink-[2]">{kb.description}</span>
        )}
      </div>
      <div className="flex items-center gap-1.5 ml-2 shrink-0">
        <span className="text-[10px] text-muted-foreground/60">{kb.document_count}</span>
        <button onClick={(e) => handlePin(kb.id, e)} className="p-0.5 hover:bg-muted rounded text-muted-foreground" title={kb.pinned ? t("kb.unpin") : t("kb.pin")}>
          {kb.pinned ? <PinOff className="w-3 h-3" /> : <Pin className="w-3 h-3" />}
        </button>
        <button onClick={(e) => handleDelete(kb.id, e)} className="p-0.5 hover:bg-red-50 rounded-md text-muted-foreground hover:text-red-500 transition-colors" title={t("docs.delete")}>
          <Trash2 className="w-3 h-3" />
        </button>
      </div>
    </div>
  );

  const renderCardItem = (kb: KnowledgeBase) => (
    <div key={kb.id} onClick={() => navigate(`/kb/${kb.id}`)}
      className="flex items-center justify-between p-4 border rounded-lg bg-card hover:border-primary/50 cursor-pointer transition-colors">
      <div className="flex items-center gap-3 min-w-0 flex-1">
        <div className="relative shrink-0">
          <FolderOpen className="w-8 h-8 text-primary" />
          {kb.pinned && <Pin className="w-3 h-3 text-amber-500 absolute -top-1 -right-1" />}
        </div>
        <div className="min-w-0 min-h-[3.5rem] flex flex-col justify-center flex-1">
          <h3 className="font-semibold truncate">{kb.name}</h3>
          <p className="text-sm text-muted-foreground line-clamp-1 break-words min-h-[1.25rem]">
            {kb.description || " "}
          </p>
          <div className="flex flex-wrap gap-x-3 gap-y-0.5 mt-1 text-xs text-muted-foreground">
            <span className="flex items-center gap-1"><FileText className="w-3 h-3" />{kb.document_count} {t("kb.docs")}</span>
            {kb.chunk_count > 0 && (
              <span className="flex items-center gap-1"><Layers className="w-3 h-3" />{kb.chunk_count} {t("kb.chunks")}</span>
            )}
            {kb.embedding_model && (
              <span className="text-[10px] bg-primary/10 text-primary px-1.5 py-0.5 rounded font-medium">{kb.embedding_model}</span>
            )}
            {kb.embedding_dim > 0 && <span>dim {kb.embedding_dim}</span>}
          </div>
        </div>
      </div>
      <div className="flex items-center gap-1 ml-3 shrink-0">
        <button onClick={(e) => handlePin(kb.id, e)} className="p-1.5 hover:bg-muted rounded-md text-muted-foreground" title={kb.pinned ? t("kb.unpin") : t("kb.pin")}>
          {kb.pinned ? <PinOff className="w-4 h-4" /> : <Pin className="w-4 h-4" />}
        </button>
        <button onClick={(e) => handleDelete(kb.id, e)} className="p-1.5 hover:bg-red-50 rounded-md text-muted-foreground hover:text-red-500 transition-colors" title={t("docs.delete")}>
          <Trash2 className="w-4 h-4" />
        </button>
      </div>
    </div>
  );

  const renderGridItem = (kb: KnowledgeBase) => (
    <div key={kb.id} onClick={() => navigate(`/kb/${kb.id}`)}
      className="flex flex-col items-center justify-between p-4 border rounded-lg bg-card hover:border-primary/50 cursor-pointer transition-colors aspect-square">
      <div className="flex flex-col items-center gap-2 min-w-0 w-full flex-1 justify-center">
        <div className="relative">
          <FolderOpen className="w-10 h-10 text-primary" />
          {kb.pinned && <Pin className="w-3.5 h-3.5 text-amber-500 absolute -top-1 -right-1" />}
        </div>
        <h3 className="font-semibold text-sm text-center truncate w-full">{kb.name}</h3>
        <p className="text-xs text-muted-foreground text-center line-clamp-1 break-words w-full h-5 overflow-hidden">
          {kb.description || " "}
        </p>
      </div>
      <div className="flex items-center justify-between w-full mt-2 pt-2 border-t">
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <span className="flex items-center gap-0.5"><FileText className="w-3 h-3" />{kb.document_count}</span>
          {kb.chunk_count > 0 && <span className="flex items-center gap-0.5"><Layers className="w-3 h-3" />{kb.chunk_count}</span>}
        </div>
        <div className="flex items-center gap-0.5">
          <button onClick={(e) => handlePin(kb.id, e)} className="p-1 hover:bg-muted rounded text-muted-foreground" title={kb.pinned ? t("kb.unpin") : t("kb.pin")}>
            {kb.pinned ? <PinOff className="w-3.5 h-3.5" /> : <Pin className="w-3.5 h-3.5" />}
          </button>
          <button onClick={(e) => handleDelete(kb.id, e)} className="p-1 hover:bg-red-50 rounded-md text-muted-foreground hover:text-red-500 transition-colors" title={t("docs.delete")}>
            <Trash2 className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>
    </div>
  );

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold">{t("kb.dashboard")}</h2>
          <p className="text-muted-foreground text-sm mt-1">{t("kb.desc")}</p>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          <button onClick={handleRefresh} className="p-2 border rounded-lg text-muted-foreground hover:bg-muted transition-colors" title="Refresh">
            <RefreshCw className="w-4 h-4" />
          </button>
          <button onClick={() => setShowCreate(true)} className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:opacity-90">
            <Plus className="w-4 h-4" />{t("kb.new")}
          </button>
        </div>
      </div>

      {showCreate && (
        <div className="mb-6 p-4 border rounded-lg bg-card">
          <h3 className="font-semibold mb-3">{t("kb.create")}</h3>
          <input type="text" placeholder={t("kb.name")} value={name} onChange={(e) => setName(e.target.value)}
            className="w-full px-3 py-2 border rounded-md mb-2 text-sm bg-background" onKeyDown={(e) => e.key === "Enter" && handleCreate()} />
          <input type="text" placeholder={t("kb.description")} value={description} onChange={(e) => setDescription(e.target.value)}
            className="w-full px-3 py-2 border rounded-md mb-3 text-sm bg-background" />
          <div className="flex gap-2">
            <button onClick={handleCreate} className="px-4 py-1.5 bg-primary text-primary-foreground rounded-md text-sm">{t("kb.createBtn")}</button>
            <button onClick={() => setShowCreate(false)} className="px-4 py-1.5 border rounded-md text-sm">{t("kb.cancel")}</button>
          </div>
        </div>
      )}

      {knowledgeBases.length > 0 && (
        <div className="flex items-center gap-2 mb-3 flex-wrap">
          <div className="flex items-center border rounded-md overflow-hidden">
            <button onClick={() => setViewMode("card")}
              className={`p-1.5 transition-colors ${viewMode === "card" ? "bg-primary/10 text-primary" : "hover:bg-muted text-muted-foreground"}`}
              title={t("kb.viewCard")}>
              <Grid3X3 className="w-3.5 h-3.5" />
            </button>
            <button onClick={() => setViewMode("grid")}
              className={`p-1.5 transition-colors ${viewMode === "grid" ? "bg-primary/10 text-primary" : "hover:bg-muted text-muted-foreground"}`}
              title={t("kb.viewGrid")}>
              <LayoutGrid className="w-3.5 h-3.5" />
            </button>
            <button onClick={() => setViewMode("compact")}
              className={`p-1.5 transition-colors ${viewMode === "compact" ? "bg-primary/10 text-primary" : "hover:bg-muted text-muted-foreground"}`}
              title={t("kb.viewCompact")}>
              <AlignJustify className="w-3.5 h-3.5" />
            </button>
          </div>
          <select value={sortMode} onChange={(e) => setSortMode(e.target.value as SortMode)}
            className="text-xs border rounded-md px-2 py-1.5 bg-card text-muted-foreground cursor-pointer">
            {sortOptions.map(o => (
              <option key={o.value} value={o.value}>{o.label}</option>
            ))}
          </select>
          <span className="text-xs text-muted-foreground ml-auto">
            {t("nav.knowledgeBaseCount").replace("{count}", String(sortedKBs.length))}
          </span>
          <button
            onClick={() => setGlobalSearchOpen(true)}
            className="p-1.5 border rounded-md text-muted-foreground hover:bg-muted hover:text-foreground transition-colors"
            title={t("search.searchAllTitle")}
          >
            <Search className="w-3.5 h-3.5" />
          </button>
        </div>
      )}

      {sortedKBs.length === 0 ? (
        <div className="text-center py-16">
          <BookOpen className="w-12 h-12 text-muted-foreground mx-auto mb-3" />
          <p className="text-muted-foreground text-lg">
            {t("kb.empty")}
          </p>
          <p className="text-muted-foreground text-sm mt-1">{t("kb.emptyHint")}</p>
        </div>
      ) : viewMode === "compact" ? (
        <div className="flex flex-col gap-0.5">
          {sortedKBs.map(kb => renderCompactItem(kb))}
        </div>
      ) : viewMode === "grid" ? (
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
          {sortedKBs.map(kb => renderGridItem(kb))}
        </div>
      ) : (
        <div className="flex flex-col gap-3">
          {sortedKBs.map(kb => renderCardItem(kb))}
        </div>
      )}

      <ConfirmDialog
        open={deleteTarget !== null}
        title={t("kb.deleteConfirm")}
        message={t("kb.deleteConfirm")}
        confirmLabel={t("docs.delete")}
        cancelLabel={t("kb.cancel")}
        onConfirm={handleDeleteConfirm}
        onCancel={() => setDeleteTarget(null)}
      />

      <GlobalSearchDialog open={globalSearchOpen} onClose={() => setGlobalSearchOpen(false)} />
    </div>
  );
}

// apps/desktop/src/components/knowledge-base/KBDashboard.vue
<script setup lang="ts">
import { ref, computed, onMounted, inject } from "vue";
import { useRouter } from "vue-router";
import { Database, Plus, Pin, PinOff, SortAsc, SortDesc, Search, Calendar } from "lucide-vue-next";
import { useKBStore, type ViewMode, type SortMode } from "@/stores/kbStore";
import { useI18n } from "@/i18n/index";

const router = useRouter();
const store = useKBStore();
const { t } = useI18n();

const showCreateDialog = ref(false);
const createName = ref("");
const createDesc = ref("");
const createLoading = ref(false);
const createError = ref("");

const openGlobalSearch = inject<() => void>("openGlobalSearch", () => {});

const sortedKBs = computed(() => store.getSortedKBs());

const sortOptions: { value: SortMode; labelKey: string }[] = [
  { value: "manual", labelKey: "kb.sortManual" },
  { value: "name-asc", labelKey: "kb.sortNameAsc" },
  { value: "name-desc", labelKey: "kb.sortNameDesc" },
  { value: "date-asc", labelKey: "kb.sortDateAsc" },
  { value: "date-desc", labelKey: "kb.sortDateDesc" },
];

const viewOptions: { value: ViewMode; label: string }[] = [
  { value: "card", label: "Card" },
  { value: "grid", label: "Grid" },
  { value: "compact", label: "Compact" },
];

onMounted(() => {
  store.loadKBs();
});

async function handleCreateKB() {
  if (!createName.value.trim()) {
    createError.value = t("kb.nameRequired");
    return;
  }
  createLoading.value = true;
  createError.value = "";
  try {
    await store.createKB(createName.value.trim(), createDesc.value.trim());
    showCreateDialog.value = false;
    createName.value = "";
    createDesc.value = "";
  } catch (e) {
    createError.value = String(e);
  } finally {
    createLoading.value = false;
  }
}

function openKB(kbId: string) {
  router.push({ name: "kb-settings", params: { kbId } });
}

function togglePin(kbId: string) {
  store.togglePinKB(kbId);
}

function formatDate(dateStr: string): string {
  try {
    return new Date(dateStr).toLocaleDateString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  } catch {
    return dateStr;
  }
}
</script>

<template>
  <div class="kb-dashboard">
    <!-- Header -->
    <div class="dashboard-header">
      <div class="header-left">
        <Database :size="22" class="header-icon" />
        <h1 class="dashboard-title">{{ t("kb.dashboard") }}</h1>
      </div>
      <div class="header-actions">
        <div class="view-select">
          <el-select
            v-model="store.viewMode"
            size="small"
            style="width: 110px"
            @change="(v: any) => store.setViewMode(v as ViewMode)"
          >
            <el-option
              v-for="opt in viewOptions"
              :key="opt.value"
              :label="t('kb.view' + opt.value.charAt(0).toUpperCase() + opt.value.slice(1))"
              :value="opt.value"
            />
          </el-select>
        </div>
        <div class="sort-select">
          <SortAsc v-if="store.sortMode === 'name-asc' || store.sortMode === 'date-asc'" :size="14" />
          <SortDesc v-else :size="14" />
          <el-select
            v-model="store.sortMode"
            size="small"
            :placeholder="t('kb.sortPlaceholder')"
            @change="(v: any) => store.setSortMode(v as SortMode)"
          >
            <el-option
              v-for="opt in sortOptions"
              :key="opt.value"
              :label="t(opt.labelKey)"
              :value="opt.value"
            />
          </el-select>
        </div>
        <el-button size="small" @click="openGlobalSearch">
          <Search :size="14" style="margin-right: 4px" />
          {{ t("search.searchAllBtn") }}
        </el-button>
        <el-button size="small" @click="showCreateDialog = true">
          <Plus :size="14" style="margin-right: 4px" />
          {{ t("kb.newBtn") }}
        </el-button>
      </div>
    </div>

    <!-- Loading -->
    <div v-if="store.loading && sortedKBs.length === 0" class="loading-state">
      <div class="loading-spinner" />
      <p>{{ t("kb.loading") }}</p>
    </div>

    <!-- Error -->
    <div v-else-if="store.error && sortedKBs.length === 0" class="error-state">
      <p class="error-text">{{ store.error }}</p>
      <el-button size="small" @click="store.loadKBs()">{{ t("kb.retry") }}</el-button>
    </div>

    <!-- Empty -->
    <div v-else-if="sortedKBs.length === 0" class="empty-state">
      <Database :size="48" class="empty-icon" />
      <p class="empty-title">{{ t("kb.empty") }}</p>
      <p class="empty-hint">{{ t("kb.emptyHintCreate") }}</p>
      <el-button type="primary" @click="showCreateDialog = true">
        <Plus :size="14" style="margin-right: 4px" />
        {{ t("kb.newBtn") }}
      </el-button>
    </div>

    <!-- KB Grid -->
    <div v-else class="kb-grid" :class="`view-${store.viewMode}`">
      <div
        v-for="kb in sortedKBs"
        :key="kb.id"
        class="kb-card"
        @click="openKB(kb.id)"
      >
        <div class="kb-card-header">
          <div class="kb-card-title-row">
            <Database :size="18" class="kb-card-icon" />
            <span class="kb-card-name">{{ kb.name }}</span>
          </div>
          <button
            class="pin-btn"
            :class="{ pinned: kb.pinned }"
            :title="kb.pinned ? t('kb.unpin') : t('kb.pin')"
            @click.stop="togglePin(kb.id)"
          >
            <Pin v-if="kb.pinned" :size="14" />
            <PinOff v-else :size="14" />
          </button>
        </div>
        <p v-if="kb.description" class="kb-card-desc">{{ kb.description }}</p>
        <div class="kb-card-stats">
          <span class="stat-item">
            <span class="stat-value">{{ kb.document_count }}</span>
            <span class="stat-label">{{ t("kb.statDocs") }}</span>
          </span>
          <span class="stat-item">
            <span class="stat-value">{{ kb.chunk_count }}</span>
            <span class="stat-label">{{ t("kb.statChunks") }}</span>
          </span>
        </div>
        <div class="kb-card-footer">
          <Calendar :size="12" />
          <span>{{ formatDate(kb.created_at) }}</span>
        </div>
      </div>
    </div>

    <!-- Create Dialog -->
    <el-dialog
      v-model="showCreateDialog"
      :title="t('kb.createDialogTitle')"
      width="420px"
      :close-on-click-modal="false"
    >
      <el-form @submit.prevent="handleCreateKB">
        <el-form-item :label="t('kb.name')" required :error="createError">
          <el-input
            v-model="createName"
            :placeholder="t('kb.namePlaceholder')"
            @keyup.enter="handleCreateKB"
          />
        </el-form-item>
        <el-form-item :label="t('kb.description')">
          <el-input
            v-model="createDesc"
            type="textarea"
            :rows="3"
            :placeholder="t('kb.descPlaceholder')"
          />
        </el-form-item>
        <el-form-item>
          <div class="dialog-actions">
            <el-button @click="showCreateDialog = false">{{ t("kb.cancel") }}</el-button>
            <el-button type="primary" :loading="createLoading" @click="handleCreateKB">
              {{ t("kb.createBtn") }}
            </el-button>
          </div>
        </el-form-item>
      </el-form>
    </el-dialog>
  </div>
</template>

<style scoped>
.kb-dashboard {
  padding: 24px;
  height: 100%;
  overflow-y: auto;
}

.dashboard-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 24px;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 10px;
}

.header-icon {
  color: var(--accent-color);
}

.dashboard-title {
  font-size: 20px;
  font-weight: 600;
  color: var(--text-primary);
  margin: 0;
}

.header-actions {
  display: flex;
  align-items: center;
  gap: 8px;
}

.view-select { display: flex; align-items: center; gap: 4px; }
.view-select :deep(.el-select) { min-width: 100px; }
.sort-select { display: flex; align-items: center; gap: 4px; color: var(--text-secondary); }
.sort-select :deep(.el-select) { min-width: 110px; }

.kb-grid { display: grid; gap: 16px; }
.kb-grid.view-card { grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); }
.kb-grid.view-grid { grid-template-columns: repeat(auto-fill, minmax(340px, 1fr)); }
.kb-grid.view-compact { grid-template-columns: 1fr; }

.kb-card {
  background: var(--surface);
  border: 1px solid var(--border-color);
  border-radius: 10px;
  padding: 16px;
  cursor: pointer;
  transition: all 150ms ease;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.kb-card:hover {
  border-color: var(--accent-color);
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.06);
}

.kb-card-header { display: flex; align-items: center; justify-content: space-between; }
.kb-card-title-row { display: flex; align-items: center; gap: 8px; min-width: 0; }
.kb-card-icon { color: var(--accent-color); flex-shrink: 0; }
.kb-card-name { font-weight: 600; font-size: 15px; color: var(--text-primary); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }

.pin-btn {
  display: flex; align-items: center; justify-content: center;
  width: 28px; height: 28px; border: none; border-radius: 6px;
  background: transparent; color: var(--text-secondary); cursor: pointer; flex-shrink: 0;
  transition: all 150ms ease;
}
.pin-btn:hover { background: var(--accent-muted); color: var(--accent-color); }
.pin-btn.pinned { color: var(--accent-color); }

.kb-card-desc { font-size: 13px; color: var(--text-secondary); margin: 0; line-height: 1.4; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
.kb-card-stats { display: flex; gap: 16px; }
.stat-item { display: flex; align-items: baseline; gap: 4px; }
.stat-value { font-size: 14px; font-weight: 600; color: var(--text-primary); }
.stat-label { font-size: 12px; color: var(--text-secondary); }
.kb-card-footer { display: flex; align-items: center; gap: 6px; font-size: 12px; color: var(--text-secondary); padding-top: 8px; border-top: 1px solid var(--border-color); }

.loading-state, .error-state, .empty-state {
  display: flex; flex-direction: column; align-items: center; justify-content: center;
  padding: 80px 24px; text-align: center; gap: 12px;
}
.loading-spinner { width: 24px; height: 24px; border: 2px solid var(--border-color); border-top-color: var(--accent-color); border-radius: 50%; animation: spin 0.6s linear infinite; }
@keyframes spin { to { transform: rotate(360deg); } }
.empty-icon { color: var(--border-color); }
.empty-title { font-size: 16px; font-weight: 500; color: var(--text-primary); margin: 0; }
.empty-hint { font-size: 13px; color: var(--text-secondary); margin: 0; }
.error-text { font-size: 13px; color: var(--destructive); margin: 0; }
.dialog-actions { display: flex; justify-content: flex-end; gap: 8px; width: 100%; }
</style>
