// apps/desktop/src/components/search/SearchInterface.tsx
import { useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { search as searchAPI } from "../../services/pythonClient";
import { useSettingsStore } from "../../stores/useSettingsStore";
import { useI18n } from "../../i18n";
import { Search, Loader2, FileText, ArrowLeft, X } from "lucide-react";
import { MarkdownRenderer } from "../common/MarkdownRenderer";
import type { SearchResult } from "../../types";

export function SearchInterface() {
  const { kbId } = useParams<{ kbId: string }>();
  const navigate = useNavigate();
  const { t } = useI18n();
  const { settings } = useSettingsStore();
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<SearchResult[]>([]);
  const [searching, setSearching] = useState(false);
  const [searchType, setSearchType] = useState<"hybrid" | "vector" | "fts">("hybrid");
  const [rerank, setRerank] = useState(true);
  const [elapsed, setElapsed] = useState(0);
  const [error, setError] = useState("");
  const [selectedChunk, setSelectedChunk] = useState<SearchResult | null>(null);

  const handleSearch = async () => {
    if (!query.trim() || !kbId) return;
    setSearching(true); setError("");
    try {
      const res = await searchAPI({ kb_id: kbId, query, search_type: searchType, top_k: 10, rerank });
      setResults(res.results); setElapsed(res.search_time_ms);
    } catch (e) { setError(String(e)); }
    setSearching(false);
  };

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <button
        onClick={() => navigate(`/kb/${kbId}`)}
        className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-4 transition-colors"
      >
        <ArrowLeft className="w-4 h-4" />
        Back
      </button>
      <h2 className="text-2xl font-bold mb-6">{t("search.title")}</h2>

      <div className="flex gap-2 mb-4">
        <div className="flex-1 relative">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
          <input type="text" value={query} onChange={(e) => setQuery(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleSearch()}
            placeholder={t("search.placeholder")}
            className="w-full pl-9 pr-4 py-2.5 border rounded-lg text-sm bg-background" />
        </div>
        <button onClick={handleSearch} disabled={searching || !query.trim()}
          className="px-6 py-2.5 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:opacity-90 disabled:opacity-50">
          {searching ? <Loader2 className="w-4 h-4 animate-spin" /> : t("search.searchBtn")}
        </button>
      </div>

      <div className="flex gap-4 mb-6 text-sm">
        <select value={searchType} onChange={(e) => setSearchType(e.target.value as any)} className="px-3 py-1.5 border rounded-md bg-background text-sm">
          <option value="hybrid">{t("search.hybrid")}</option>
          <option value="vector">{t("search.vector")}</option>
          <option value="fts">{t("search.fts")}</option>
        </select>
        <label className="flex items-center gap-2 text-sm">
          <input type="checkbox" checked={rerank} onChange={(e) => setRerank(e.target.checked)} className="rounded" />
          {t("search.rerank")}
        </label>
        {rerank && settings.rerank_model && (
          <span className="text-[10px] bg-muted px-1.5 py-0.5 rounded self-center">{settings.rerank_model}</span>
        )}
      </div>

      {error && <div className="p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700 mb-4">{error}</div>}

      {results.length > 0 && (
        <p className="text-xs text-muted-foreground mb-3">{t("search.results", { count: results.length, time: elapsed })}</p>
      )}

      <div className="space-y-3">
        {results.map((r) => (
          <div
            key={r.chunk_id}
            className="p-4 border rounded-lg bg-card cursor-pointer hover:border-primary/50 transition-colors"
            onClick={() => setSelectedChunk(r)}
          >
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <FileText className="w-4 h-4 text-primary" />
                <span className="text-sm font-medium">{r.doc_name}</span>
              </div>
              <span className="text-xs bg-primary/10 text-primary px-2 py-0.5 rounded-full font-mono">
                {(r.score * 100).toFixed(0)}%
              </span>
            </div>
            <div className="max-h-32 overflow-hidden relative">
              <MarkdownRenderer className="prose prose-sm max-w-none dark:prose-invert text-muted-foreground">
                {r.content}
              </MarkdownRenderer>
              <div className="absolute bottom-0 left-0 right-0 h-8 bg-gradient-to-t from-card to-transparent pointer-events-none" />
            </div>
            {r.metadata?.page && (
              <p className="text-xs text-muted-foreground mt-2">{t("search.page")} {r.metadata.page}</p>
            )}
          </div>
        ))}
      </div>

      {/* Chunk detail dialog */}
      {selectedChunk && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onClick={() => setSelectedChunk(null)}>
          <div className="bg-card border rounded-xl shadow-xl max-w-2xl w-full mx-4 max-h-[80vh] flex flex-col" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between p-4 border-b shrink-0">
              <div className="flex items-center gap-3 min-w-0">
                <FileText className="w-5 h-5 text-primary shrink-0" />
                <div className="min-w-0">
                  <h3 className="font-semibold text-sm truncate">{selectedChunk.doc_name}</h3>
                  <p className="text-xs text-muted-foreground">
                    {selectedChunk.metadata?.page != null && <span>{t("search.page")} {selectedChunk.metadata.page} · </span>}
                    {selectedChunk.metadata?.chunk_index != null && <span>{t("search.chunkIndex", { index: selectedChunk.metadata.chunk_index })} · </span>}
                    <span className="font-mono text-primary">{(selectedChunk.score * 100).toFixed(1)}%</span>
                  </p>
                </div>
              </div>
              <button onClick={() => setSelectedChunk(null)} className="p-1 hover:bg-muted rounded-md shrink-0">
                <X className="w-5 h-5" />
              </button>
            </div>
            <div className="p-6 overflow-y-auto flex-1">
              <MarkdownRenderer className="prose prose-sm max-w-none dark:prose-invert">
                {selectedChunk.content}
              </MarkdownRenderer>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// apps/desktop/src/components/search/SearchInterface.vue
<script setup lang="ts">
import { ref, computed, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { search } from "@/services/pythonClient";
import type { SearchResult, SearchRequest } from "@/types";
import {
  Search,
  Settings2,
  SlidersHorizontal,
  RotateCcw,
  FileText,
  Hash,
  ExternalLink,
  X,
  Loader2,
} from "lucide-vue-next";
import { useI18n } from "@/i18n/index";
import MarkdownRenderer from "@/components/common/MarkdownRenderer.vue";

const { t } = useI18n();

const props = withDefaults(
  defineProps<{
    kbId?: string;
  }>(),
  { kbId: undefined }
);

const route = useRoute();
const router = useRouter();

const resolvedKbId = computed(() => props.kbId || (route.params.kbId as string));

const query = ref("");
const searchType = ref<"hybrid" | "vector" | "fts">("hybrid");
const topK = ref(10);
const rerank = ref(true);
const contextWindow = ref(1);

const results = ref<SearchResult[]>([]);
const total = ref(0);
const searchTimeMs = ref(0);
const searching = ref(false);
const searched = ref(false);
const error = ref<string | null>(null);

// Chunk detail dialog
const showChunkDetail = ref(false);
const selectedChunk = ref<SearchResult | null>(null);
const chunkContent = ref("");
const chunkLoading = ref(false);

// Validate params
watch(resolvedKbId, () => {
  results.value = [];
  searched.value = false;
  error.value = null;
});

async function doSearch() {
  const kbId = resolvedKbId.value;
  if (!kbId || !query.value.trim()) return;

  searching.value = true;
  searched.value = false;
  error.value = null;
  results.value = [];
  total.value = 0;

  const req: SearchRequest = {
    kb_id: kbId,
    query: query.value.trim(),
    search_type: searchType.value,
    top_k: topK.value,
    rerank: rerank.value,
    context_window: contextWindow.value,
  };

  try {
    const res = await search(req);
    results.value = res.results;
    total.value = res.total;
    searchTimeMs.value = res.search_time_ms;
  } catch (e: any) {
    error.value = e?.message ?? String(e);
  } finally {
    searching.value = false;
    searched.value = true;
  }
}

function openChunkDetail(result: SearchResult) {
  selectedChunk.value = result;
  chunkContent.value = result.content;
  showChunkDetail.value = true;
}

function navigateToDocument(result: SearchResult) {
  const kbId = resolvedKbId.value;
  if (kbId && result.doc_id) {
    router.push(`/kb/${kbId}/documents/${result.doc_id}`);
  }
}

function truncate(text: string, max = 300): string {
  if (text.length <= max) return text;
  return text.slice(0, max) + "...";
}

function scoreColor(score: number): string {
  if (score >= 0.7) return "var(--el-color-success)";
  if (score >= 0.4) return "var(--el-color-warning)";
  return "var(--el-color-danger)";
}
</script>

<template>
  <div class="search-interface">
    <!-- Search Form -->
    <div class="search-form">
      <div class="search-row">
        <el-input
          v-model="query"
          :placeholder="t('search.placeholder')"
          clearable
          size="large"
          @keydown.enter="doSearch"
        >
          <template #prefix>
            <Search :size="18" class="input-icon" />
          </template>
          <template #append>
            <el-button
              type="primary"
              :loading="searching"
              @click="doSearch"
            >
              <template v-if="!searching">
                <Search :size="16" style="margin-right: 4px" />
                {{ t("search.searchBtn") }}
              </template>
              <template v-else>
                <Loader2 :size="16" class="spin" style="margin-right: 4px" />
                {{ t("search.searching") || "Searching" }}
              </template>
            </el-button>
          </template>
        </el-input>
      </div>

      <div class="search-options">
        <div class="option-item">
          <label class="option-label">
            <Settings2 :size="14" />
            {{ t("search.searchType") || "Search Type" }}
          </label>
          <el-select v-model="searchType" size="small" style="width: 140px">
            <el-option :label="t('search.hybrid')" value="hybrid" />
            <el-option :label="t('search.vector')" value="vector" />
            <el-option :label="t('search.fts')" value="fts" />
          </el-select>
        </div>

        <div class="option-item">
          <label class="option-label">
            <Hash :size="14" />
            {{ t("search.topK") || "Top-K" }} ({{ topK }})
          </label>
          <el-slider
            v-model="topK"
            :min="3"
            :max="50"
            :step="1"
            show-input
            size="small"
            input-size="small"
            style="width: 200px"
          />
        </div>

        <div class="option-item">
          <label class="option-label">
            <RotateCcw :size="14" />
            {{ t("search.rerank") }}
          </label>
          <el-switch v-model="rerank" size="small" />
        </div>

        <div class="option-item">
          <label class="option-label">
            <SlidersHorizontal :size="14" />
            {{ t("search.contextWindow") }} ({{ contextWindow }})
          </label>
          <el-slider
            v-model="contextWindow"
            :min="0"
            :max="5"
            :step="1"
            show-input
            size="small"
            input-size="small"
            style="width: 140px"
          />
        </div>
      </div>
    </div>

    <!-- Results -->
    <div class="search-results-area">
      <!-- Error -->
      <el-alert
        v-if="error"
        :title="error"
        type="error"
        show-icon
        closable
        class="mb-3"
      />

      <!-- Summary -->
      <div v-if="searched && !error" class="result-summary">
        {{ t("search.results", { count: total, time: searchTimeMs }) }}
      </div>

      <!-- Loading -->
      <div v-if="searching" class="loading-state">
        <el-skeleton :rows="5" animated />
      </div>

      <!-- Empty -->
      <el-empty
        v-else-if="searched && results.length === 0"
        :description="t('search.noResults')"
        :image-size="80"
      />

      <!-- Results List -->
      <div v-else-if="results.length > 0" class="results-list">
        <div
          v-for="(result, idx) in results"
          :key="result.chunk_id || idx"
          class="result-card"
          @click="openChunkDetail(result)"
        >
          <div class="result-header">
            <span class="result-title" @click.stop="navigateToDocument(result)">
              <FileText :size="14" />
              {{ result.doc_name || (t("search.untitled") || "Untitled") }}
            </span>
            <el-tag
              :style="{
                backgroundColor: scoreColor(result.score),
                borderColor: scoreColor(result.score),
                color: '#fff',
                fontSize: '11px',
              }"
              size="small"
            >
              {{ (result.score * 100).toFixed(1) }}%
            </el-tag>
          </div>
          <div class="result-content">
            <MarkdownRenderer :content="truncate(result.content, 400)" />
          </div>
          <div class="result-footer">
            <span v-if="result.page_start != null" class="page-info">
              {{ t("search.page") }} {{ result.page_start }}{{ result.page_end != null && result.page_end !== result.page_start ? `-${result.page_end}` : "" }}
            </span>
            <button class="view-doc-btn" @click.stop="navigateToDocument(result)">
              <ExternalLink :size="12" />
              {{ t("search.openDocument") || "Open Document" }}
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Chunk Detail Dialog -->
    <el-dialog
      v-model="showChunkDetail"
      :title="t('search.chunkDetail')"
      width="700px"
      destroy-on-close
    >
      <template v-if="selectedChunk">
        <div class="chunk-meta">
          <el-descriptions :column="2" size="small" border>
            <el-descriptions-item :label="t('search.selectDoc') || 'Document'">
              {{ selectedChunk.doc_name }}
            </el-descriptions-item>
            <el-descriptions-item :label="t('search.score') || 'Score'">
              <el-tag
                :style="{
                  backgroundColor: scoreColor(selectedChunk.score),
                  borderColor: scoreColor(selectedChunk.score),
                  color: '#fff',
                }"
                size="small"
              >
                {{ (selectedChunk.score * 100).toFixed(1) }}%
              </el-tag>
            </el-descriptions-item>
            <el-descriptions-item
              v-if="selectedChunk.page_start != null"
              :label="t('search.page')"
            >
              {{ selectedChunk.page_start }}
              {{ selectedChunk.page_end != null && selectedChunk.page_end !== selectedChunk.page_start ? `- ${selectedChunk.page_end}` : "" }}
            </el-descriptions-item>
            <el-descriptions-item
              v-if="selectedChunk.metadata?.chunk_index != null"
              :label="t('search.chunkIndexLabel') || 'Chunk Index'"
            >
              {{ selectedChunk.metadata.chunk_index }}
            </el-descriptions-item>
          </el-descriptions>
        </div>
        <div class="chunk-content">
          <MarkdownRenderer :content="selectedChunk.content" />
        </div>
      </template>
      <template #footer>
        <el-button @click="showChunkDetail = false">{{ t("kb.cancel") }}</el-button>
        <el-button
          v-if="selectedChunk"
          type="primary"
          @click="navigateToDocument(selectedChunk); showChunkDetail = false"
        >
          <ExternalLink :size="14" style="margin-right: 4px" />
          {{ t("search.openDocument") || "Open Document" }}
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<style scoped>
.search-interface {
  display: flex;
  flex-direction: column;
  gap: 16px;
  height: 100%;
}

.search-form {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 16px;
  background: var(--el-bg-color);
  border-radius: var(--el-border-radius-base);
  border: 1px solid var(--el-border-color-light);
}

.search-row {
  display: flex;
  gap: 8px;
}

.search-row .el-input {
  flex: 1;
}

.input-icon {
  color: var(--el-text-color-placeholder);
}

.search-options {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  align-items: flex-start;
}

.option-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.option-label {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 12px;
  color: var(--el-text-color-secondary);
  font-weight: 500;
}

.search-results-area {
  flex: 1;
  overflow-y: auto;
  padding: 0 4px;
}

.result-summary {
  font-size: 13px;
  color: var(--el-text-color-secondary);
  margin-bottom: 12px;
  padding: 0 4px;
}

.loading-state {
  padding: 24px 0;
}

.results-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.result-card {
  padding: 12px 14px;
  background: var(--el-bg-color);
  border: 1px solid var(--el-border-color-light);
  border-radius: var(--el-border-radius-base);
  cursor: pointer;
  transition: all 0.15s ease;
}

.result-card:hover {
  border-color: var(--el-color-primary);
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.06);
}

.result-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 6px;
}

.result-title {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 13px;
  font-weight: 600;
  color: var(--el-color-primary);
}

.result-content {
  font-size: 13px;
  line-height: 1.6;
  color: var(--el-text-color-regular);
  word-break: break-word;
  margin-bottom: 8px;
  display: -webkit-box;
  -webkit-line-clamp: 4;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.result-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.page-info {
  font-size: 11px;
  color: var(--el-text-color-disabled);
  font-family: monospace;
}

.view-doc-btn {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 11px;
  color: var(--el-color-info);
  background: none;
  border: none;
  cursor: pointer;
  padding: 2px 6px;
  border-radius: 4px;
  transition: background 0.15s;
}

.view-doc-btn:hover {
  background: var(--el-fill-color-light);
  color: var(--el-color-primary);
}

/* Chunk Detail Dialog */
.chunk-meta {
  margin-bottom: 16px;
}

.chunk-content {
  max-height: 500px;
  overflow-y: auto;
  background: var(--el-fill-color-lighter);
  border: 1px solid var(--el-border-color-light);
  border-radius: var(--el-border-radius-base);
  padding: 12px;
}

.spin {
  animation: spin 1s linear infinite;
}

@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.mb-3 {
  margin-bottom: 12px;
}
</style>
