// apps/desktop/src/components/layout/Sidebar.tsx
import { useEffect, useState, useMemo, useRef, useCallback } from "react";
import { Link, useLocation, useParams, useNavigate } from "react-router-dom";
import { useKBStore } from "../../stores/useKBStore";
import { useSettingsStore } from "../../stores/useSettingsStore";
import { useChatStore } from "../../stores/useChatStore";
import { useI18n } from "../../i18n";
import { BookOpen, Settings, FolderOpen, AlertCircle, X, Layers, Pin, MessageSquare, Plus, ChevronDown, ChevronRight, LayoutDashboard, Pencil, Check, Trash2, PanelLeftClose, PanelLeft } from "lucide-react";

const COLLAPSED_KEY = "skb-sidebar-collapsed";

export function Sidebar() {
  const location = useLocation();
  const navigate = useNavigate();
  const { kbId } = useParams();
  const { knowledgeBases, loadKBs, getSortedKBs, sortMode } = useKBStore();
  const { pythonRunning, pythonError } = useSettingsStore();
  const { conversations, activeConversationId, setActiveConversation, newConversation, deleteConversation, renameConversation, load: loadChats } = useChatStore();
  useEffect(() => { loadChats(); }, [loadChats]);
  const { t } = useI18n();
  const [showError, setShowError] = useState(false);
  const [kbExpanded, setKbExpanded] = useState(true);
  const [chatExpanded, setChatExpanded] = useState(true);
  const [renamingId, setRenamingId] = useState<string | null>(null);
  const [renameDraft, setRenameDraft] = useState("");
  const [chatPopover, setChatPopover] = useState(false);
  const chatBtnRef = useRef<HTMLButtonElement>(null);
  const popoverRef = useRef<HTMLDivElement>(null);

  // Close chat popover on outside click / Escape
  useEffect(() => {
    if (!chatPopover) return;
    const handler = (e: MouseEvent) => {
      const target = e.target as Node;
      if (chatBtnRef.current?.contains(target)) return;       // button click → toggle
      if (popoverRef.current?.contains(target)) return;       // inside popover → ignore
      setChatPopover(false);
    };
    const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") setChatPopover(false); };
    document.addEventListener("mousedown", handler);
    document.addEventListener("keydown", onKey);
    return () => { document.removeEventListener("mousedown", handler); document.removeEventListener("keydown", onKey); };
  }, [chatPopover]);

  const [collapsed, setCollapsed] = useState(() => {
    try { return localStorage.getItem(COLLAPSED_KEY) === "true"; } catch { return false; }
  });

  const toggleCollapsed = () => {
    setCollapsed((prev) => {
      const next = !prev;
      try { localStorage.setItem(COLLAPSED_KEY, String(next)); } catch {}
      return next;
    });
  };

  useEffect(() => { loadKBs(); }, []);
  const isActive = (path: string) => location.pathname === path || location.pathname.startsWith(path + "/");
  const sortedKBs = useMemo(() => getSortedKBs(), [knowledgeBases, sortMode]);
  const recentConversations = useMemo(() => conversations, [conversations]);

  // ── collapsed icon-only mode ──
  if (collapsed) {
    return (
      <>
        <aside className="w-14 bg-card border-r flex flex-col shrink-0 items-center py-3 gap-1 rounded-r-xl">
          {/* App icon → home */}
          <button onClick={() => navigate("/")} title={t("app.title")}
            className="p-2 hover:bg-muted rounded-lg text-muted-foreground hover:text-foreground transition-colors">
            <BookOpen className="w-5 h-5 text-primary" />
          </button>

          {/* Backend status dot */}
          <span className={`w-2 h-2 rounded-full shrink-0 mt-1 ${pythonRunning ? "bg-green-500" : "bg-red-500"}`}
            title={pythonRunning ? t("app.backendReady") : t("app.backendOffline")} />

          <div className="flex-1 flex flex-col items-center gap-1 mt-2 w-full px-1.5">
            {/* Overview */}
            <button onClick={() => navigate("/")}
              title={t("nav.overview")}
              className={`p-2 rounded-lg transition-colors w-full flex justify-center ${isActive("/") && !kbId ? "bg-primary/10 text-primary" : "hover:bg-muted text-muted-foreground"}`}>
              <LayoutDashboard className="w-4 h-4" />
            </button>

            {/* KB list — show as icon buttons */}
            {sortedKBs.slice(0, 8).map((kb) => (
              <button key={kb.id} onClick={() => navigate(`/kb/${kb.id}`)}
                title={kb.name}
                className={`p-2 rounded-lg transition-colors w-full flex justify-center ${kbId === kb.id ? "bg-primary/10 text-primary" : "hover:bg-muted text-muted-foreground"}`}>
                {kb.pinned ? <Pin className="w-4 h-4 text-amber-500" /> : <Layers className="w-4 h-4" />}
              </button>
            ))}

            {/* Chat — floating popover when collapsed */}
            <div className="relative">
              <button onClick={() => setChatPopover(!chatPopover)}
                ref={chatBtnRef}
                title={t("nav.chat")}
                className={`p-2 rounded-lg transition-colors w-full flex justify-center ${location.pathname.startsWith("/chat") ? "bg-primary/10 text-primary" : "hover:bg-muted text-muted-foreground"}`}>
                <MessageSquare className="w-4 h-4" />
              </button>
              {chatPopover && (
                <div ref={popoverRef} className="fixed z-50 w-64 bg-card border rounded-xl shadow-xl overflow-hidden"
                  style={{ left: (chatBtnRef.current?.getBoundingClientRect().right ?? 60) + 8, top: (chatBtnRef.current?.getBoundingClientRect().top ?? 100) - 4 }}>
                  <div className="flex items-center justify-between px-3 py-2 border-b bg-muted/50">
                    <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">{t("nav.chat")}</span>
                    <button onClick={(e) => { e.stopPropagation(); const id = newConversation(); navigate(`/chat/${id}`); setChatPopover(false); }}
                      className="p-0.5 hover:bg-background rounded" title={t("chat.new")}>
                      <Plus className="w-3.5 h-3.5" />
                    </button>
                  </div>
                  <div className="max-h-64 overflow-y-auto">
                    {recentConversations.length === 0 ? (
                      <p className="text-xs text-muted-foreground px-3 py-4 text-center">{t("chat.empty")}</p>
                    ) : (
                      recentConversations.map((conv) => (
                        <Link key={conv.id} to={`/chat/${conv.id}`}
                          onClick={() => { setActiveConversation(conv.id); setChatPopover(false); }}
                          className={`flex items-center gap-2 px-3 py-2 text-sm transition-colors truncate ${activeConversationId === conv.id && location.pathname.startsWith("/chat") ? "bg-primary/10 text-primary font-medium" : "hover:bg-muted text-muted-foreground"}`}>
                          <MessageSquare className="w-3 h-3 shrink-0" />
                          <span className="truncate text-xs">{conv.title || conv.messages[0]?.content?.slice(0, 40) || t("chat.new")}</span>
                        </Link>
                      ))
                    )}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Settings */}
          <button onClick={() => navigate("/settings")}
            title={t("nav.settings")}
            className={`p-2 rounded-lg transition-colors w-full flex justify-center ${isActive("/settings") ? "bg-primary/10 text-primary" : "hover:bg-muted text-muted-foreground"}`}>
            <Settings className="w-4 h-4" />
          </button>

          {/* Expand button */}
          <button onClick={toggleCollapsed}
            title="Expand sidebar"
            className="p-2 hover:bg-muted rounded-lg text-muted-foreground mt-auto">
            <PanelLeft className="w-4 h-4" />
          </button>
        </aside>

        {/* Error Dialog — same as expanded mode */}
        {showError && pythonError && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onClick={() => setShowError(false)}>
            <div className="bg-card border rounded-xl shadow-xl max-w-lg w-full mx-4 p-6" onClick={(e) => e.stopPropagation()}>
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-semibold flex items-center gap-2">
                  <AlertCircle className="w-5 h-5 text-red-500" />
                  {t("app.backendError")}
                </h3>
                <button onClick={() => setShowError(false)} className="hover:bg-muted rounded-md p-1"><X className="w-4 h-4" /></button>
              </div>
              <pre className="text-xs bg-muted p-4 rounded-lg overflow-auto max-h-80 whitespace-pre-wrap break-all">{pythonError}</pre>
            </div>
          </div>
        )}
      </>
    );
  }

  // ── expanded full mode ──
  return (
    <>
      <aside className="w-56 bg-card border-r flex flex-col shrink-0 rounded-r-xl">
        {/* App title + status */}
        <div className="p-4 border-b shrink-0">
          <div className="flex items-center justify-between">
            <h1 className="text-sm font-semibold flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-primary" />
              {t("app.title")}
            </h1>
            <button onClick={toggleCollapsed}
              className="p-1 hover:bg-muted rounded text-muted-foreground"
              title="Collapse sidebar">
              <PanelLeftClose className="w-3.5 h-3.5" />
            </button>
          </div>
          <div className="flex items-center gap-1 mt-1">
            <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${pythonRunning ? "bg-green-500" : "bg-red-500"}`} />
            <span className="text-xs text-muted-foreground">
              {pythonRunning ? t("app.backendReady") : t("app.backendOffline")}
            </span>
          </div>
          {pythonError && (
            <button onClick={() => setShowError(true)} className="flex items-center gap-1 mt-1 text-xs text-amber-600 hover:text-amber-700 cursor-pointer">
              <AlertCircle className="w-3 h-3" />
              {t("app.viewError")}
            </button>
          )}
        </div>

        {/* Middle section — CSS Grid, two equal rows */}
        <div className="flex-1 min-h-0 py-2 px-2" style={{ display: "grid", gridTemplateRows: "1fr 1fr", gap: "0.25rem" }}>
          {/* ══════ KB Section ══════ */}
          <div className="flex flex-col overflow-hidden" style={{ minHeight: 0 }}>
            <button onClick={() => setKbExpanded(!kbExpanded)}
              className="w-full flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm transition-colors hover:bg-muted text-muted-foreground shrink-0">
              {kbExpanded ? <ChevronDown className="w-3 h-3" /> : <ChevronRight className="w-3 h-3" />}
              <FolderOpen className="w-4 h-4" />
              <span className="flex-1 text-left">{t("nav.knowledgeBases")}</span>
            </button>
            {kbExpanded && (
              <div className="ml-2 border-l border-border/50 pl-2 mt-0.5 overflow-y-auto flex-1 min-h-0">
                <Link to="/"
                  className={`flex items-center gap-1.5 px-2 py-1.5 rounded-md text-sm transition-colors ${isActive("/") && !kbId ? "bg-primary/10 text-primary font-medium" : "hover:bg-muted text-muted-foreground"}`}>
                  <LayoutDashboard className="w-3 h-3 shrink-0" />
                  {t("nav.overview")}
                </Link>
                {sortedKBs.map((kb) => (
                  <Link key={kb.id} to={`/kb/${kb.id}`} title={kb.description || undefined}
                    className={`flex items-center gap-1.5 px-2 py-1.5 rounded-md text-sm transition-colors ${kbId === kb.id ? "bg-primary/10 text-primary font-medium" : "hover:bg-muted text-muted-foreground"}`}>
                    {kb.pinned ? <Pin className="w-2.5 h-2.5 text-amber-500 shrink-0" /> : <Layers className="w-3 h-3 shrink-0" />}
                    <span className="truncate">{kb.name}</span>
                    <span className="text-[10px] text-muted-foreground/60 ml-auto shrink-0">{kb.document_count}</span>
                  </Link>
                ))}
              </div>
            )}
          </div>

          {/* ══════ Chat Section ══════ */}
          <div className="flex flex-col overflow-hidden" style={{ minHeight: 0 }}>
            <button onClick={() => setChatExpanded(!chatExpanded)}
              className="w-full flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm transition-colors hover:bg-muted text-muted-foreground shrink-0">
              {chatExpanded ? <ChevronDown className="w-3 h-3" /> : <ChevronRight className="w-3 h-3" />}
              <MessageSquare className="w-4 h-4" />
              <span className="flex-1 text-left">{t("nav.chat")}</span>
              <button onClick={(e) => { e.stopPropagation(); setChatExpanded(true); const id = newConversation(); navigate(`/chat/${id}`); }}
                className="p-0.5 hover:bg-background rounded" title={t("chat.new")}>
                <Plus className="w-3 h-3" />
              </button>
            </button>
            {chatExpanded && (
              <div className="ml-2 border-l border-border/50 pl-2 mt-0.5 overflow-y-auto flex-1 min-h-0">
                {recentConversations.length === 0 ? (
                  <p className="text-xs text-muted-foreground px-2 py-1">{t("chat.empty")}</p>
                ) : (
                  recentConversations.map((conv) => (
                    <div key={conv.id} className="group relative">
                      {renamingId === conv.id ? (
                        <div className="flex items-center gap-1 px-2 py-1.5">
                          <input autoFocus value={renameDraft}
                            onChange={(e) => setRenameDraft(e.target.value)}
                            onKeyDown={(e) => {
                              if (e.key === "Enter") { renameConversation(conv.id, renameDraft); setRenamingId(null); }
                              if (e.key === "Escape") setRenamingId(null);
                            }}
                            onBlur={() => { renameConversation(conv.id, renameDraft); setRenamingId(null); }}
                            className="text-xs bg-background border rounded px-1.5 py-0.5 flex-1 outline-none ring-1 ring-primary" />
                        </div>
                      ) : (
                        <Link to={`/chat/${conv.id}`} onClick={() => setActiveConversation(conv.id)}
                          className={`flex items-center gap-1.5 px-2 py-1.5 rounded-md text-sm transition-colors truncate ${activeConversationId === conv.id && location.pathname.startsWith("/chat") ? "bg-primary/10 text-primary font-medium" : "hover:bg-muted text-muted-foreground"}`}>
                          <MessageSquare className="w-3 h-3 shrink-0" />
                          <span className="truncate text-xs flex-1">{conv.title || conv.messages[0]?.content?.slice(0, 30) || t("chat.new")}</span>
                        </Link>
                      )}
                      <div className="absolute right-1 top-1/2 -translate-y-1/2 hidden group-hover:flex items-center gap-0.5">
                        <button onClick={(e) => { e.preventDefault(); e.stopPropagation(); setRenamingId(conv.id); setRenameDraft(conv.title || ""); }}
                          className="p-0.5 hover:bg-muted rounded text-muted-foreground/60" title={t("kb.rename")}>
                          <Pencil className="w-2.5 h-2.5" />
                        </button>
                        <button onClick={(e) => { e.preventDefault(); e.stopPropagation(); deleteConversation(conv.id); }}
                          className="p-0.5 hover:bg-red-50 rounded text-muted-foreground/60 hover:text-red-500" title={t("docs.delete")}>
                          <Trash2 className="w-2.5 h-2.5" />
                        </button>
                      </div>
                    </div>
                  ))
                )}
              </div>
            )}
          </div>
        </div>

        {/* Settings — fixed to bottom */}
        <div className="p-2 border-t shrink-0">
          <Link to="/settings"
            className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm transition-colors ${isActive("/settings") ? "bg-primary/10 text-primary font-medium" : "hover:bg-muted text-muted-foreground"}`}>
            <Settings className="w-4 h-4" />
            {t("nav.settings")}
          </Link>
        </div>
      </aside>

      {/* Error Dialog */}
      {showError && pythonError && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onClick={() => setShowError(false)}>
          <div className="bg-card border rounded-xl shadow-xl max-w-lg w-full mx-4 p-6" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-semibold flex items-center gap-2">
                <AlertCircle className="w-5 h-5 text-red-500" />
                {t("app.backendError")}
              </h3>
              <button onClick={() => setShowError(false)} className="hover:bg-muted rounded-md p-1"><X className="w-4 h-4" /></button>
            </div>
            <pre className="text-xs bg-muted p-4 rounded-lg overflow-auto max-h-80 whitespace-pre-wrap break-all">{pythonError}</pre>
          </div>
        </div>
      )}
    </>
  );
}

// apps/desktop/src/components/layout/Sidebar.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from "vue";
import { useRouter, useRoute } from "vue-router";
import {
  BookOpen,
  Settings,
  FolderOpen,
  Layers,
  Pin,
  MessageSquare,
  Plus,
  ChevronDown,
  ChevronRight,
  LayoutDashboard,
  Pencil,
  Check,
  Trash2,
  PanelLeftClose,
  PanelLeft,
  AlertCircle,
  X,
} from "lucide-vue-next";
import { useKBStore } from "@/stores/kbStore";
import { useSettingsStore } from "@/stores/settingsStore";
import { useChatStore } from "@/stores/chatStore";
import { useTabStore } from "@/stores/tabStore";
import { useI18n } from "@/i18n/index";
import type { KnowledgeBase } from "@/types";

const COLLAPSED_KEY = "skb-sidebar-collapsed";

const router = useRouter();
const route = useRoute();
const kbStore = useKBStore();
const settingsStore = useSettingsStore();
const chatStore = useChatStore();
const tabStore = useTabStore();
const { t } = useI18n();

const kbId = computed(() => route.params.kbId as string | undefined);

// ── Collapse state ──
const collapsed = ref(false);
try {
  collapsed.value = localStorage.getItem(COLLAPSED_KEY) === "true";
} catch {
  /* ignore */
}

function toggleCollapsed() {
  collapsed.value = !collapsed.value;
  try {
    localStorage.setItem(COLLAPSED_KEY, String(collapsed.value));
  } catch {
    /* ignore */
  }
}

// ── Section expand/collapse ──
const kbExpanded = ref(true);
const chatExpanded = ref(true);

// ── Chat rename ──
const renamingId = ref<string | null>(null);
const renameDraft = ref("");

// ── Chat popover (collapsed mode) ──
const chatPopover = ref(false);
const chatBtnRef = ref<HTMLButtonElement | null>(null);
const popoverRef = ref<HTMLDivElement | null>(null);

// ── Python error dialog ──
const showError = ref(false);

// ── Close popover on outside click / Escape ──
function onDocumentClick(e: MouseEvent) {
  if (!chatPopover.value) return;
  const target = e.target as Node;
  if (chatBtnRef.value?.contains(target)) return;
  if (popoverRef.value?.contains(target)) return;
  chatPopover.value = false;
}
function onKeyDown(e: KeyboardEvent) {
  if (e.key === "Escape") chatPopover.value = false;
}

watch(chatPopover, (val) => {
  if (val) {
    document.addEventListener("mousedown", onDocumentClick);
    document.addEventListener("keydown", onKeyDown);
  } else {
    document.removeEventListener("mousedown", onDocumentClick);
    document.removeEventListener("keydown", onKeyDown);
  }
});

// ── Load ──
onMounted(() => {
  kbStore.loadKBs();
  chatStore.load();
});

// ── Computed ──
const sortedKBs = computed(() => kbStore.getSortedKBs());
const recentConversations = computed(() => chatStore.conversations);

function isActive(path: string) {
  return route.path === path || route.path.startsWith(path + "/");
}

// ── Actions ──
function newConversation() {
  const id = chatStore.newConversation();
  return id;
}

function startNewChat() {
  const id = newConversation();
  router.push(`/chat/${id}`);
  chatPopover.value = false;
}

function startNewChatExpanded() {
  chatExpanded.value = true;
  const id = newConversation();
  router.push(`/chat/${id}`);
}

function startRename(convId: string, title: string) {
  renamingId.value = convId;
  renameDraft.value = title || "";
}

function commitRename(convId: string) {
  if (renameDraft.value.trim()) {
    chatStore.renameConversation(convId, renameDraft.value.trim());
  }
  renamingId.value = null;
}

function handleDeleteConversation(convId: string) {
  chatStore.deleteConversation(convId);
  const tab = useTabStore().tabs.find((t) => t.id === convId);
  if (tab) useTabStore().closeTab(tab.id);
  if (convId === chatStore.activeConversationId || route.path === `/chat/${convId}`) {
    const remaining = chatStore.conversations.filter((c) => c.id !== convId);
    if (remaining.length > 0) {
      router.replace(`/chat/${remaining[0].id}`);
    } else {
      const id = newConversation();
      router.replace(`/chat/${id}`);
    }
  }
}
</script>

<template>
  <!-- ═══════ Collapsed mode ═══════ -->
  <template v-if="collapsed">
    <aside class="sidebar sidebar-collapsed">
      <!-- Top: expand button -->
      <button
        class="sb-icon-btn"
        :title="t('nav.expandSidebar')"
        @click="toggleCollapsed"
      >
        <PanelLeft :size="16" />
      </button>

      <!-- Backend status -->
      <span
        class="sb-status-dot"
        :class="settingsStore.pythonRunning ? 'bg-green' : 'bg-red'"
        :title="settingsStore.pythonRunning ? t('app.backendReady') : t('app.backendOffline')"
      />

      <div class="sb-icon-list">
        <!-- Overview -->
        <button
          class="sb-icon-btn"
          :class="{ active: isActive('/') && !kbId }"
          :title="t('nav.overview')"
          @click="router.push('/')"
        >
          <LayoutDashboard :size="16" />
        </button>

        <!-- KBs -->
        <button
          v-for="kb in sortedKBs.slice(0, 8)"
          :key="kb.id"
          class="sb-icon-btn"
          :class="{ active: kbId === kb.id }"
          :title="kb.name"
          @click="router.push(`/kb/${kb.id}`)"
        >
          <Pin v-if="kb.pinned" :size="16" class="text-amber-500" />
          <Layers v-else :size="16" />
        </button>

        <!-- Chat popover -->
        <div class="sb-popover-host">
          <button
            ref="chatBtnRef"
            class="sb-icon-btn"
            :class="{ active: route.path.startsWith('/chat') }"
            :title="t('nav.chatSection')"
            @click="chatPopover = !chatPopover"
          >
            <MessageSquare :size="16" />
          </button>
          <div
            v-if="chatPopover"
            ref="popoverRef"
            class="sb-popover"
          >
            <div class="sb-popover-header">
              <span class="sb-popover-title">{{ t("nav.chatSection") }}</span>
              <button
                class="sb-icon-btn-xs"
                :title="t('nav.newChat')"
                @click="startNewChat"
              >
                <Plus :size="14" />
              </button>
            </div>
            <div class="sb-popover-list">
              <p v-if="recentConversations.length === 0" class="sb-empty-text">
                {{ t("nav.noConversations") }}
              </p>
              <div
                v-for="conv in recentConversations"
                :key="conv.id"
                class="sb-popover-item group"
              >
                <router-link
                  :to="`/chat/${conv.id}`"
                  class="sb-popover-link"
                  :class="{
                    active:
                      chatStore.activeConversationId === conv.id &&
                      route.path.startsWith('/chat'),
                  }"
                  @click="
                    chatStore.setActiveConversation(conv.id);
                    tabStore.openTab({
                      id: conv.id,
                      title: conv.title || conv.messages[0]?.content?.slice(0, 30) || t('chat.new'),
                      url: `/chat/${conv.id}`,
                    });
                    chatPopover = false;
                  "
                >
                  <MessageSquare :size="12" class="shrink-0" />
                  <span class="truncate">
                    {{
                      conv.title ||
                      conv.messages[0]?.content?.slice(0, 40) ||
                      t("chat.new")
                    }}
                  </span>
                </router-link>
                <button
                  class="sb-popover-delete"
                  @click.prevent.stop="handleDeleteConversation(conv.id)"
                  :title="t('kb.deleteTooltip')"
                >
                  <Trash2 :size="10" />
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Bottom: Settings -->
      <div class="sb-bottom">
        <button
          class="sb-icon-btn"
          :class="{ active: isActive('/settings') }"
          :title="t('nav.settings')"
          @click="router.push('/settings')"
        >
          <Settings :size="16" />
        </button>
      </div>

      <!-- Error dialog -->
      <Teleport to="body">
        <div
          v-if="showError && settingsStore.pythonError"
          class="modal-overlay"
          @click="showError = false"
        >
          <div class="modal-card" @click.stop>
            <div class="modal-header">
              <h3 class="modal-title">
                <AlertCircle :size="20" class="text-red-500" />
                {{ t("app.backendError") }}
              </h3>
              <button class="sb-icon-btn-xs" @click="showError = false">
                <X :size="16" />
              </button>
            </div>
            <pre class="modal-error">{{ settingsStore.pythonError }}</pre>
          </div>
        </div>
      </Teleport>
    </aside>
  </template>

  <!-- ═══════ Expanded mode ═══════ -->
  <template v-else>
    <aside class="sidebar sidebar-expanded">
      <!-- App header -->
      <div class="sb-header">
        <div class="sb-header-row">
          <h1 class="sb-app-title">
            <BookOpen :size="16" class="text-primary" />
            {{ t("nav.superKb") }}
          </h1>
          <button
            class="sb-icon-btn-xs"
            :title="t('nav.collapseSidebar')"
            @click="toggleCollapsed"
          >
            <PanelLeftClose :size="14" />
          </button>
        </div>
        <div class="sb-status-row">
          <span
            class="sb-status-dot"
            :class="settingsStore.pythonRunning ? 'bg-green' : 'bg-red'"
          />
          <span class="sb-status-text">
            {{ settingsStore.pythonRunning ? t("app.backendReady") : t("app.backendOffline") }}
          </span>
        </div>
        <button
          v-if="settingsStore.pythonError"
          class="sb-error-link"
          @click="showError = true"
        >
          <AlertCircle :size="12" />
          {{ t("nav.viewError") }}
        </button>
      </div>

      <!-- Middle: KB + Chat sections -->
      <div class="sb-middle">
        <!-- KB Section -->
        <div class="sb-section">
          <button class="sb-section-header" @click="kbExpanded = !kbExpanded">
            <ChevronDown v-if="kbExpanded" :size="12" />
            <ChevronRight v-else :size="12" />
            <FolderOpen :size="16" />
            <span class="sb-section-label">{{ t("nav.knowledgeBases") }}</span>
          </button>
          <div v-if="kbExpanded" class="sb-section-list">
            <router-link
              to="/"
              class="sb-item"
              :class="{ active: isActive('/') && !kbId }"
            >
              <LayoutDashboard :size="12" class="shrink-0" />
              {{ t("nav.overview") }}
            </router-link>
            <router-link
              v-for="kb in sortedKBs"
              :key="kb.id"
              :to="`/kb/${kb.id}`"
              class="sb-item"
              :class="{ active: kbId === kb.id }"
              :title="kb.description || undefined"
            >
              <Pin
                v-if="kb.pinned"
                :size="10"
                class="text-amber-500 shrink-0"
              />
              <Layers v-else :size="12" class="shrink-0" />
              <span class="truncate">{{ kb.name }}</span>
              <span class="sb-item-count">{{ kb.document_count }}</span>
            </router-link>
          </div>
        </div>

        <!-- Chat Section -->
        <div class="sb-section">
          <div
            class="sb-section-header"
            role="button"
            tabindex="0"
            @click="chatExpanded = !chatExpanded"
            @keydown.enter="chatExpanded = !chatExpanded"
          >
            <ChevronDown v-if="chatExpanded" :size="12" />
            <ChevronRight v-else :size="12" />
            <MessageSquare :size="16" />
            <span class="sb-section-label">{{ t("nav.chatSection") }}</span>
            <button
              class="sb-icon-btn-xs ml-auto"
              :title="t('nav.newChat')"
              @click.stop="startNewChatExpanded"
            >
              <Plus :size="12" />
            </button>
          </div>
          <div v-if="chatExpanded" class="sb-section-list">
            <p
              v-if="recentConversations.length === 0"
              class="sb-empty-text"
            >
              {{ t("nav.noConversations") }}
            </p>
            <div
              v-for="conv in recentConversations"
              :key="conv.id"
              class="sb-chat-item group"
            >
              <template v-if="renamingId === conv.id">
                <div class="flex items-center gap-1 px-2 py-1">
                  <input
                    v-model="renameDraft"
                    class="sb-rename-input"
                    autofocus
                    @keydown.enter="commitRename(conv.id)"
                    @keydown.escape="renamingId = null"
                    @blur="commitRename(conv.id)"
                  />
                </div>
              </template>
              <template v-else>
                <router-link
                  :to="`/chat/${conv.id}`"
                  class="sb-item"
                  :class="{
                    active:
                      chatStore.activeConversationId === conv.id &&
                      route.path.startsWith('/chat'),
                  }"
                  @click="
                    chatStore.setActiveConversation(conv.id);
                    tabStore.openTab({
                      id: conv.id,
                      title: conv.title || conv.messages[0]?.content?.slice(0, 30) || t('chat.new'),
                      url: `/chat/${conv.id}`,
                    });
                  "
                >
                  <MessageSquare :size="12" class="shrink-0" />
                  <span class="truncate">
                    {{
                      conv.title ||
                      conv.messages[0]?.content?.slice(0, 30) ||
                      t("chat.new")
                    }}
                  </span>
                </router-link>
                <div class="sb-chat-actions">
                  <button
                    class="sb-icon-btn-xs"
                    @click.prevent.stop="
                      startRename(conv.id, conv.title)
                    "
                    :title="t('nav.renameTooltip')"
                  >
                    <Pencil :size="10" />
                  </button>
                  <button
                    class="sb-icon-btn-xs hover:text-red-500"
                    @click.prevent.stop="handleDeleteConversation(conv.id)"
                    :title="t('kb.deleteTooltip')"
                  >
                    <Trash2 :size="10" />
                  </button>
                </div>
              </template>
            </div>
          </div>
        </div>
      </div>

      <!-- Settings footer -->
      <div class="sb-footer">
        <router-link
          to="/settings"
          class="sb-item"
          :class="{ active: isActive('/settings') }"
        >
          <Settings :size="16" />
          {{ t("nav.settings") }}
        </router-link>
      </div>
    </aside>

    <!-- Error dialog -->
    <Teleport to="body">
      <div
        v-if="showError && settingsStore.pythonError"
        class="modal-overlay"
        @click="showError = false"
      >
        <div class="modal-card" @click.stop>
          <div class="modal-header">
            <h3 class="modal-title">
              <AlertCircle :size="20" class="text-red-500" />
              {{ t("app.backendError") }}
            </h3>
            <button class="sb-icon-btn-xs" @click="showError = false">
              <X :size="16" />
            </button>
          </div>
          <pre class="modal-error">{{ settingsStore.pythonError }}</pre>
        </div>
      </div>
    </Teleport>
  </template>
</template>

<style scoped>
/* ── Base Sidebar ── */
.sidebar {
  display: flex;
  flex-direction: column;
  background: var(--el-bg-color);
  border-right: 1px solid var(--el-border-color-lighter);
  flex-shrink: 0;
  overflow: hidden;
  height: 100%;
  transition: width 250ms cubic-bezier(0.4, 0, 0.2, 1);
}

.sidebar-collapsed {
  width: 52px;
  align-items: center;
  padding: 8px 0;
  gap: 4px;
}

.sidebar-expanded {
  width: 240px;
}

/* ── Icon buttons ── */
.sb-icon-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  border: none;
  border-radius: 8px;
  background: transparent;
  color: var(--el-text-color-secondary);
  cursor: pointer;
  transition: all 120ms;
}
.sb-icon-btn:hover {
  background: var(--el-fill-color);
  color: var(--el-text-color-primary);
}
.sb-icon-btn.active {
  background: var(--el-color-primary-light-9);
  color: var(--el-color-primary);
}

.sb-icon-btn-xs {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  border: none;
  border-radius: 4px;
  background: transparent;
  color: var(--el-text-color-secondary);
  cursor: pointer;
  transition: all 120ms;
}
.sb-icon-btn-xs:hover {
  background: var(--el-fill-color);
}

/* ── Status dot ── */
.sb-status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  flex-shrink: 0;
}
.bg-green {
  background: var(--el-color-success);
}
.bg-red {
  background: var(--el-color-danger);
}
.text-primary {
  color: var(--el-color-primary);
}
.text-amber-500 {
  color: #f59e0b;
}
.text-red-500 {
  color: var(--el-color-danger);
}

/* ── Icon list (collapsed) ── */
.sb-icon-list {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 2px;
  padding: 4px;
  width: 100%;
  overflow-y: auto;
}

.sb-bottom {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 2px;
  width: 100%;
  padding: 4px;
}

/* ── Popover (collapsed) ── */
.sb-popover-host {
  position: relative;
}

.sb-popover {
  position: fixed;
  z-index: 100;
  width: 240px;
  max-height: 300px;
  background: var(--surface);
  border: 1px solid var(--border-color);
  border-radius: 12px;
  box-shadow: 0 8px 30px rgba(0, 0, 0, 0.12);
  overflow: visible;
  left: 60px;
  top: auto;
  margin-top: -8px;
}

.sb-popover::before {
  content: '';
  position: absolute;
  left: -5px;
  top: 14px;
  width: 10px;
  height: 10px;
  background: var(--surface);
  border-left: 1px solid var(--border-color);
  border-bottom: 1px solid var(--border-color);
  transform: rotate(45deg);
}

.sb-popover-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 8px 12px;
  border-bottom: 1px solid var(--el-border-color-lighter);
  background: var(--el-fill-color-lighter);
}

.sb-popover-title {
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  color: var(--el-text-color-secondary);
}

.sb-popover-list {
  max-height: 240px;
  overflow-y: auto;
}

.sb-popover-item {
  position: relative;
  display: flex;
}

.sb-popover-link {
  flex: 1;
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 12px;
  font-size: 12px;
  color: var(--el-text-color-secondary);
  text-decoration: none;
  transition: all 120ms;
  overflow: hidden;
}
.sb-popover-link:hover {
  background: var(--el-fill-color);
}
.sb-popover-link.active {
  background: var(--el-color-primary-light-9);
  color: var(--el-color-primary);
  font-weight: 500;
}

.sb-popover-delete {
  display: none;
  position: absolute;
  right: 4px;
  top: 50%;
  transform: translateY(-50%);
  width: 20px;
  height: 20px;
  border: none;
  border-radius: 4px;
  background: transparent;
  color: var(--el-text-color-disabled);
  cursor: pointer;
}
.group:hover .sb-popover-delete {
  display: flex;
  align-items: center;
  justify-content: center;
}
.sb-popover-delete:hover {
  background: var(--el-color-danger-light-9);
  color: var(--el-color-danger);
}

/* ── Expanded Header ── */
.sb-header {
  padding: 12px;
  border-bottom: 1px solid var(--el-border-color-lighter);
  flex-shrink: 0;
}

.sb-header-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.sb-app-title {
  font-size: 14px;
  font-weight: 700;
  margin: 0;
  display: flex;
  align-items: center;
  gap: 6px;
}

.sb-status-row {
  display: flex;
  align-items: center;
  gap: 6px;
  margin-top: 6px;
}

.sb-status-text {
  font-size: 11px;
  color: var(--el-text-color-disabled);
}

.sb-error-link {
  display: flex;
  align-items: center;
  gap: 4px;
  margin-top: 4px;
  font-size: 11px;
  color: #d97706;
  background: none;
  border: none;
  cursor: pointer;
  padding: 0;
}
.sb-error-link:hover {
  color: #b45309;
}

/* ── Middle section ── */
.sb-middle {
  flex: 1;
  display: grid;
  grid-template-rows: 1fr 1fr;
  gap: 2px;
  padding: 4px;
  overflow: hidden;
  min-height: 0;
}

/* ── Sections ── */
.sb-section {
  display: flex;
  flex-direction: column;
  overflow: hidden;
  min-height: 0;
}

.sb-section-header {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 10px;
  border: none;
  border-radius: 6px;
  background: transparent;
  color: var(--el-text-color-secondary);
  cursor: pointer;
  font-size: 13px;
  transition: all 120ms;
  flex-shrink: 0;
}
.sb-section-header:hover {
  background: var(--el-fill-color);
}

.sb-section-label {
  flex: 1;
  text-align: left;
}

.ml-auto {
  margin-left: auto;
}

.sb-section-list {
  margin-left: 8px;
  border-left: 1px solid var(--el-border-color-lighter);
  padding-left: 4px;
  overflow-y: auto;
  flex: 1;
  min-height: 0;
}

/* ── Items ── */
.sb-item {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 5px 8px;
  border-radius: 6px;
  font-size: 12px;
  color: var(--el-text-color-secondary);
  text-decoration: none;
  transition: all 120ms;
  overflow: hidden;
}
.sb-item:hover {
  background: var(--el-fill-color);
  color: var(--el-text-color-primary);
}
.sb-item.active {
  background: var(--el-color-primary-light-9);
  color: var(--el-color-primary);
  font-weight: 500;
}

.sb-item-count {
  font-size: 10px;
  color: var(--el-text-color-disabled);
  margin-left: auto;
  flex-shrink: 0;
}

.sb-empty-text {
  font-size: 11px;
  color: var(--el-text-color-disabled);
  padding: 4px 8px;
  margin: 0;
}

/* ── Chat items ── */
.sb-chat-item {
  position: relative;
  display: flex;
}

.sb-chat-actions {
  display: none;
  position: absolute;
  right: 4px;
  top: 50%;
  transform: translateY(-50%);
  gap: 2px;
  align-items: center;
}
.group:hover .sb-chat-actions {
  display: flex;
}

.sb-rename-input {
  font-size: 11px;
  padding: 2px 6px;
  border: 1px solid var(--el-color-primary);
  border-radius: 4px;
  outline: none;
  flex: 1;
  background: var(--el-bg-color);
}

/* ── Footer ── */
.sb-footer {
  padding: 4px;
  border-top: 1px solid var(--el-border-color-lighter);
  flex-shrink: 0;
}

/* ── Modal ── */
.modal-overlay {
  position: fixed;
  inset: 0;
  z-index: 200;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(0, 0, 0, 0.5);
}

.modal-card {
  background: var(--el-bg-color);
  border: 1px solid var(--el-border-color);
  border-radius: 12px;
  box-shadow: 0 8px 30px rgba(0, 0, 0, 0.18);
  max-width: 500px;
  width: 90%;
  max-height: 80vh;
  display: flex;
  flex-direction: column;
}

.modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px;
  border-bottom: 1px solid var(--el-border-color-lighter);
}

.modal-title {
  font-size: 15px;
  font-weight: 600;
  margin: 0;
  display: flex;
  align-items: center;
  gap: 8px;
}

.modal-error {
  font-size: 11px;
  padding: 16px;
  margin: 0;
  overflow-y: auto;
  white-space: pre-wrap;
  word-break: break-all;
  background: var(--el-fill-color-lighter);
  flex: 1;
  max-height: 400px;
}

/* ── Utilities ── */
.truncate {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.shrink-0 {
  flex-shrink: 0;
}
.flex-1 {
  flex: 1;
}
.items-center {
  align-items: center;
}
.gap-1 {
  gap: 4px;
}
.px-2 {
  padding-left: 8px;
  padding-right: 8px;
}
.py-1 {
  padding-top: 4px;
  padding-bottom: 4px;
}
.mt-auto {
  margin-top: auto;
}
</style>
