// apps/desktop/src/components/layout/TitleBar.vue
<template>
  <div class="titlebar" @mousedown="onDrag" data-tauri-drag-region>
    <div class="titlebar-left">
      <span class="titlebar-app-name">SKB</span>
    </div>

    <div class="titlebar-center">
      <slot name="center" />
    </div>

    <div class="titlebar-right">
      <!-- User Guide -->
      <button class="titlebar-icon-btn" title="Guide" @click="showGuide = true">
        <BookOpen :size="14" />
      </button>

      <!-- Tab Bar Toggle -->
      <button
        v-if="tabStore.tabs.length > 0"
        class="titlebar-icon-btn"
        :class="{ 'titlebar-icon-btn-active': !tabStore.tabBarVisible }"
        :title="tabStore.tabBarVisible ? 'Hide tab bar' : 'Show tab bar'"
        @click="tabStore.toggleTabBar"
      >
        <PanelTop :size="14" />
      </button>

      <!-- Theme Toggle -->
      <button class="titlebar-icon-btn" :title="themeTitle" @click="cycleTheme">
        <Sun v-if="theme === 'light'" :size="14" />
        <Moon v-else-if="theme === 'dark'" :size="14" />
        <Monitor v-else :size="14" />
      </button>

      <!-- Language Toggle -->
      <button
        class="titlebar-icon-btn titlebar-lang-btn"
        :title="locale === 'en' ? '切换到中文' : 'Switch to English'"
        @click="toggleLocale"
      >
        <Globe :size="14" />
      </button>

      <!-- Window Controls -->
      <button class="titlebar-win-btn" title="Minimize" @click="win.minimize()">
        <Minus :size="14" />
      </button>
      <button class="titlebar-win-btn" title="Maximize" @click="win.toggleMaximize()">
        <Square :size="12" />
      </button>
      <button class="titlebar-win-btn titlebar-win-btn-close" title="Close" @click="win.close()">
        <X :size="14" />
      </button>
    </div>

    <!-- User Guide Dialog -->
    <UserGuideDialog :visible="showGuide" @update:visible="showGuide = $event" />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { Minus, Square, X, Sun, Moon, Monitor, Globe, BookOpen, PanelTop } from "lucide-vue-next";
import { useSettingsStore } from "@/stores/settingsStore";
import { useTabStore } from "@/stores/tabStore";
import { useI18n } from "@/i18n/index";
import UserGuideDialog from "@/components/common/UserGuideDialog.vue";

const win = getCurrentWindow();
const settingsStore = useSettingsStore();
const tabStore = useTabStore();
const { t, locale, toggleLocale } = useI18n();

const theme = ref<"light" | "dark" | "system">("system");
const showGuide = ref(false);

const themeTitle = ref("");

onMounted(async () => {
  // Sync theme from settings
  theme.value = (settingsStore.settings.theme as any) || "system";
  applyTheme();
  updateThemeTitle();

  // First-launch detection
  const s = settingsStore.settings;
  const isFresh = !s.embedding_api_key && !s.mineru_token && !s.llm_api_key;
  if (isFresh) {
    setTimeout(() => { showGuide.value = true; }, 600);
  }
});

function applyTheme() {
  const root = document.documentElement;
  const media = window.matchMedia("(prefers-color-scheme: dark)");
  const isDark = theme.value === "dark" || (theme.value === "system" && media.matches);
  root.classList.toggle("dark", isDark);
}

function cycleTheme() {
  const order: Array<"light" | "dark" | "system"> = ["light", "dark", "system"];
  const idx = order.indexOf(theme.value);
  theme.value = order[(idx + 1) % 3];
  applyTheme();
  updateThemeTitle();
  settingsStore.saveSettings({ ...settingsStore.settings, theme: theme.value });
}

function updateThemeTitle() {
  const titles: Record<string, string> = { light: "Light", dark: "Dark", system: "System" };
  themeTitle.value = titles[theme.value] || "Theme";
}

async function onDrag(e: MouseEvent) {
  const target = e.target as HTMLElement;
  if (target.closest("button, .titlebar-icon-btn, .titlebar-win-btn")) return;
  try { await win.startDragging(); } catch {}
}
</script>

<style scoped>
.titlebar {
  display: flex;
  align-items: center;
  height: 36px;
  background: var(--surface);
  border-bottom: 1px solid var(--border-color);
  user-select: none;
  flex-shrink: 0;
  padding: 0 6px;
}

.titlebar-left {
  display: flex;
  align-items: center;
  gap: 6px;
  min-width: 60px;
  padding-left: 8px;
}

.titlebar-app-name {
  font-size: 12px;
  font-weight: 500;
  color: var(--text-secondary);
  letter-spacing: 0.3px;
}

.titlebar-center {
  flex: 1;
  display: flex;
  align-items: center;
  min-width: 0;
  height: 100%;
}

.titlebar-right {
  display: flex;
  align-items: center;
  gap: 0;
  min-width: 180px;
  justify-content: flex-end;
}

.titlebar-icon-btn {
  width: 36px;
  height: 36px;
  display: flex;
  align-items: center;
  justify-content: center;
  border: none;
  background: transparent;
  color: var(--text-secondary);
  cursor: pointer;
  transition: background 120ms ease, color 120ms ease;
}

.titlebar-icon-btn:hover {
  background: var(--surface-raised);
  color: var(--text-primary);
}

.titlebar-icon-btn-active {
  background: var(--accent-muted);
  color: var(--accent-color);
}

.titlebar-lang-btn {
  font-size: 11px;
  font-weight: 500;
}

.titlebar-win-btn {
  width: 44px;
  height: 36px;
  display: flex;
  align-items: center;
  justify-content: center;
  border: none;
  background: transparent;
  color: var(--text-secondary);
  cursor: pointer;
  transition: background 120ms ease, color 120ms ease;
}

.titlebar-win-btn:hover {
  background: var(--surface-raised);
  color: var(--text-primary);
}

.titlebar-win-btn-close:hover {
  background: #e81123;
  color: #ffffff;
}
</style>

// apps/desktop/src/components/layout/TitleBar.tsx
import { useEffect, useState } from "react";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { Minus, Square, X, Globe, Sun, Moon, Monitor, BookOpen, PanelTop } from "lucide-react";
import { useI18n } from "../../i18n";
import { useSettingsStore } from "../../stores/useSettingsStore";
import { useTabStore } from "../../stores/useTabStore";
import { UserGuideDialog } from "../common/UserGuideDialog";

type Theme = "light" | "dark" | "system";

const THEME_ICONS: Record<Theme, React.ReactNode> = {
  light: <Sun className="w-3.5 h-3.5" />,
  dark: <Moon className="w-3.5 h-3.5" />,
  system: <Monitor className="w-3.5 h-3.5" />,
};

const THEME_NEXT: Record<Theme, Theme> = {
  light: "dark",
  dark: "system",
  system: "light",
};

const THEME_TITLES: Record<Theme, string> = {
  light: "浅色模式",
  dark: "深色模式",
  system: "跟随系统",
};

function useTheme() {
  const theme = useSettingsStore((s) => s.settings.theme) as Theme;
  const saveSettings = useSettingsStore((s) => s.saveSettings);
  const settings = useSettingsStore((s) => s.settings);

  useEffect(() => {
    const root = document.documentElement;
    const media = window.matchMedia("(prefers-color-scheme: dark)");

    const apply = () => {
      const isDark = theme === "dark" || (theme === "system" && media.matches);
      root.classList.toggle("dark", isDark);
    };

    apply();
    media.addEventListener("change", apply);
    return () => media.removeEventListener("change", apply);
  }, [theme]);

  const cycle = () => {
    const next = THEME_NEXT[theme];
    saveSettings({ ...settings, theme: next });
  };

  return { theme, cycle };
}

export function TitleBar() {
  const win = getCurrentWindow();
  const { t, lang, setLang } = useI18n();
  const { theme, cycle } = useTheme();
  const tabBarVisible = useTabStore((s) => s.tabBarVisible);
  const tabsCount = useTabStore((s) => s.tabs.length);
  const toggleTabBar = useTabStore((s) => s.toggleTabBar);

  const [showGuide, setShowGuide] = useState(false);
  const [checkedFirstLaunch, setCheckedFirstLaunch] = useState(false);

  // First-launch detection: if settings are all at defaults, auto-open the guide
  useEffect(() => {
    if (checkedFirstLaunch) return;
    const s = useSettingsStore.getState().settings;
    const isFresh = !s.embedding_api_key && !s.mineru_token && !s.llm_api_key;
    if (isFresh) {
      setCheckedFirstLaunch(true);
      // Small delay so the UI is ready
      const timer = setTimeout(() => setShowGuide(true), 600);
      return () => clearTimeout(timer);
    }
    setCheckedFirstLaunch(true);
  }, [checkedFirstLaunch]);

  const toggleLang = () => setLang(lang === "en" ? "zh-CN" : "en");

  return (
    <div
      data-tauri-drag-region
      className="title-bar flex items-center justify-between h-9 bg-card border-b shrink-0 select-none"
    >
      <div className="flex items-center gap-2 pl-3">
        <span className="text-xs font-medium text-muted-foreground">
          {t("app.title")}
        </span>
      </div>

      <div className="flex h-full">
        <button
          onClick={() => setShowGuide(true)}
          className="w-10 h-full flex items-center justify-center hover:bg-muted transition-colors"
          title={t("app.guide")}
        >
          <BookOpen className="w-3.5 h-3.5 text-muted-foreground" />
        </button>
        {tabsCount > 0 && (
          <button
            onClick={toggleTabBar}
            className={`w-10 h-full flex items-center justify-center hover:bg-muted transition-colors ${!tabBarVisible ? "bg-primary/10 text-primary" : "text-muted-foreground"}`}
            title={tabBarVisible ? "Hide tab bar" : "Show tab bar"}
          >
            <PanelTop className="w-3.5 h-3.5" />
          </button>
        )}
        <button
          onClick={() => cycle()}
          className="w-10 h-full flex items-center justify-center hover:bg-muted transition-colors"
          title={THEME_TITLES[theme]}
        >
          {THEME_ICONS[theme]}
        </button>
        <button
          onClick={toggleLang}
          className="w-10 h-full flex items-center justify-center hover:bg-muted transition-colors text-xs font-medium text-muted-foreground"
          title={lang === "en" ? "切换到中文" : "Switch to English"}
        >
          <Globe className="w-3.5 h-3.5" />
        </button>
        <button
          onClick={() => win.minimize()}
          className="w-10 h-full flex items-center justify-center hover:bg-muted transition-colors"
        >
          <Minus className="w-3.5 h-3.5 text-muted-foreground" />
        </button>
        <button
          onClick={() => win.toggleMaximize()}
          className="w-10 h-full flex items-center justify-center hover:bg-muted transition-colors"
        >
          <Square className="w-3 h-3 text-muted-foreground" />
        </button>
        <button
          onClick={() => win.close()}
          className="w-10 h-full flex items-center justify-center hover:bg-red-500 hover:text-white transition-colors"
        >
          <X className="w-3.5 h-3.5 text-muted-foreground" />
        </button>
      </div>
      {showGuide && <UserGuideDialog onClose={() => setShowGuide(false)} />}
    </div>
  );
}
