// apps/desktop/src/components/chat/ChatInput.tsx
import { Send, Square } from "lucide-react";

interface ChatInputProps {
  input: string;
  setInput: (v: string) => void;
  streaming: boolean;
  onSend: (text?: string) => void;
  onStop: () => void;
  placeholder: string;
}

export function ChatInput({ input, setInput, streaming, onSend, onStop, placeholder }: ChatInputProps) {
  return (
    <div className="px-6 py-4 border-t shrink-0 bg-card/30">
      <div className="flex gap-2">
        <textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); onSend(); } }}
          placeholder={placeholder}
          rows={2}
          disabled={streaming}
          className="flex-1 px-4 py-2.5 border rounded-xl text-sm bg-background resize-none focus:outline-none focus:ring-2 focus:ring-primary disabled:opacity-50"
        />
        {streaming ? (
          <button onClick={onStop}
            className="px-4 bg-red-500 text-white rounded-xl hover:bg-red-600 shrink-0 self-stretch flex items-center justify-center">
            <Square className="w-4 h-4" />
          </button>
        ) : (
          <button onClick={() => onSend()} disabled={!input.trim()}
            className="px-4 bg-primary text-primary-foreground rounded-xl hover:opacity-90 disabled:opacity-50 shrink-0 self-stretch flex items-center justify-center">
            <Send className="w-4 h-4" />
          </button>
        )}
      </div>
    </div>
  );
}

// apps/desktop/src/components/chat/ChatInput.vue
<template>
  <div class="chat-input-container">
    <el-input
      v-model="inputText"
      type="textarea"
      :autosize="{ minRows: 1, maxRows: 6 }"
      :placeholder="placeholder"
      class="chat-textarea"
      :disabled="streaming"
      @keydown.enter.exact.prevent="handleSend"
    />
    <div class="chat-input-actions">
      <el-button
        v-if="streaming"
        type="danger"
        size="small"
        round
        class="stop-btn"
        @click="emit('stop')"
      >
        <Ban class="w-4 h-4 mr-1" />
        Stop
      </el-button>
      <el-button
        v-else
        type="primary"
        size="small"
        round
        class="send-btn"
        :disabled="!canSend"
        @click="handleSend"
      >
        <SendHorizontal class="w-4 h-4 mr-1" />
        Send
      </el-button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import { Ban, SendHorizontal } from "lucide-vue-next";

const props = withDefaults(
  defineProps<{
    streaming?: boolean;
    placeholder?: string;
  }>(),
  { streaming: false, placeholder: "Type a message..." }
);

const emit = defineEmits<{
  send: [content: string];
  stop: [];
}>();

const inputText = ref("");

const canSend = computed(() => inputText.value.trim().length > 0);

function handleSend() {
  if (props.streaming || !canSend.value) return;
  const trimmed = inputText.value.trim();
  if (!trimmed) return;
  emit("send", trimmed);
  inputText.value = "";
}
</script>

<style scoped>
.chat-input-container {
  @apply flex flex-col gap-2 p-4 border-t border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900;
}

.chat-textarea {
  @apply resize-none;
}

.chat-textarea :deep(.el-textarea__inner) {
  @apply bg-gray-50 dark:bg-gray-800 border-gray-200 dark:border-gray-700
         text-gray-900 dark:text-gray-100 rounded-xl
         placeholder:text-gray-400 dark:placeholder:text-gray-500
         text-sm leading-relaxed;
}

.chat-input-actions {
  @apply flex justify-end items-center gap-2;
}

.send-btn,
.stop-btn {
  @apply flex items-center;
}
</style>
