// apps/desktop/src/components/chat/ChatMessageList.tsx
import { useRef, useEffect } from "react";
import { useVirtualizer } from "@tanstack/react-virtual";
import type { ChatMessage, SearchResult } from "../../types";
import { MessageRow } from "./MessageRow";

interface ChatMessageListProps {
  messages: ChatMessage[];
  streaming: boolean;
  toolResults: Record<string, string>;
  activeToolId: string | null;
  setPreviewChunk: (s: SearchResult | null) => void;
  copiedMsgIdx: number | null;
  handleCopy: (c: string, i: number) => void;
  autoScroll: boolean;
  onToggleAutoScroll: () => void;
  scrollRef: React.RefObject<HTMLDivElement | null>;
}

export function ChatMessageList({
  messages, streaming, toolResults, activeToolId, setPreviewChunk,
  copiedMsgIdx, handleCopy, autoScroll, scrollRef,
}: ChatMessageListProps) {
  const visibleMessages = messages.filter((m) => m.role !== "tool");
  const prevLenRef = useRef(visibleMessages.length);
  const prevContentRef = useRef(messages[messages.length - 1]?.content);

  const virtualizer = useVirtualizer({
    count: visibleMessages.length,
    getScrollElement: () => scrollRef.current,
    estimateSize: () => 120,
    overscan: 5,
  });

  // Auto-scroll to bottom during streaming or when autoScroll is true
  useEffect(() => {
    if (visibleMessages.length === 0) return;

    const lastMsg = messages[messages.length - 1];
    const contentChanged = lastMsg?.content !== prevContentRef.current;
    const lenChanged = visibleMessages.length !== prevLenRef.current;

    prevLenRef.current = visibleMessages.length;
    prevContentRef.current = lastMsg?.content;

    if (!lenChanged && !contentChanged) return;
    if (!autoScroll && !streaming) return;

    // Use double RAF to ensure virtualizer has measured new items
    const raf = requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        virtualizer.scrollToIndex(visibleMessages.length - 1, { align: "end" });
      });
    });
    return () => cancelAnimationFrame(raf);
  }, [visibleMessages.length, streaming, messages[messages.length - 1]?.content]);

  // Trigger initial scroll to bottom on mount
  useEffect(() => {
    if (visibleMessages.length > 1) {
      const raf = requestAnimationFrame(() => {
        virtualizer.scrollToIndex(visibleMessages.length - 1, { align: "end" });
      });
      return () => cancelAnimationFrame(raf);
    }
  }, []);

  return (
    <div
      style={{
        height: `${virtualizer.getTotalSize()}px`,
        width: "100%",
        position: "relative",
      }}
    >
      {virtualizer.getVirtualItems().map((virtualItem) => {
        const msg = visibleMessages[virtualItem.index];
        const isLast = virtualItem.index === visibleMessages.length - 1;
        const isStreaming = streaming && isLast && msg.role === "assistant";

        return (
          <div
            key={virtualItem.key}
            data-index={virtualItem.index}
            ref={virtualizer.measureElement}
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: "100%",
              transform: `translateY(${virtualItem.start}px)`,
            }}
            className="pb-4"
          >
            <MessageRow
              msg={msg}
              i={virtualItem.index}
              isStreaming={isStreaming}
              isLast={isLast}
              streaming={streaming}
              toolResults={toolResults}
              activeToolId={activeToolId}
              setPreviewChunk={setPreviewChunk}
              copiedMsgIdx={copiedMsgIdx}
              handleCopy={handleCopy}
            />
          </div>
        );
      })}
    </div>
  );
}

// apps/desktop/src/components/chat/ChatMessageList.vue
<template>
  <div ref="listContainer" class="message-list-container">
    <div
      ref="virtualizerContainer"
      class="virtual-list"
      :style="{ height: `${virtualizer.getTotalSize()}px` }"
    >
      <div
        v-for="vRow in virtualizer.getVirtualItems()"
        :key="String(vRow.key)"
        class="virtual-row"
        :style="{
          transform: `translateY(${vRow.start}px)`,
        }"
      >
        <MessageRow
          :msg="visibleMessages[vRow.index]"
          :index="vRow.index"
          :is-streaming="isStreaming && vRow.index === visibleMessages.length - 1 && visibleMessages[vRow.index].role === 'assistant'"
          :is-last="vRow.index === visibleMessages.length - 1"
          :streaming="streaming"
          :tool-results="toolResults"
          :active-tool-id="activeToolId"
          :copied-msg-idx="copiedMsgIdx"
          @source-click="(src: any) => $emit('sourceClick', src)"
          @copy="(content: string, idx: number) => $emit('copy', content, idx)"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch, nextTick, onMounted, onUnmounted } from "vue";
import { useVirtualizer } from "@tanstack/vue-virtual";
import type { ChatMessage, SearchResult } from "@/types";
import MessageRow from "./MessageRow.vue";

const props = withDefaults(
  defineProps<{
    messages: ChatMessage[];
    streaming?: boolean;
    toolResults?: Record<string, string>;
    activeToolId?: string | null;
    copiedMsgIdx?: number | null;
    autoScroll?: boolean;
    scrollRef?: HTMLElement | null;
  }>(),
  {
    streaming: false,
    toolResults: () => ({}),
    activeToolId: null,
    copiedMsgIdx: null,
    autoScroll: true,
    scrollRef: null,
  }
);

defineEmits<{
  sourceClick: [source: SearchResult];
  copy: [content: string, idx: number];
  toggleAutoScroll: [];
}>();

const listContainer = ref<HTMLDivElement | null>(null);
const virtualizerContainer = ref<HTMLDivElement | null>(null);

const visibleMessages = computed(() =>
  props.messages.filter((m) => m.role !== "tool")
);

const isStreaming = computed(() => props.streaming);

const virtualizer = useVirtualizer({
  count: visibleMessages.value.length,
  getScrollElement: () => props.scrollRef || listContainer.value,
  estimateSize: (i: number) => {
    const m = visibleMessages.value[i];
    if (!m) return 120;
    if (m.role === "user") return 60;
    if (m.tool_calls) return 140;
    return 160;
  },
  overscan: 3,
}) as any;

// Auto-scroll to bottom during streaming or when autoScroll is true
const prevLenRef = ref(visibleMessages.value.length);
const prevContentRef = ref(props.messages[props.messages.length - 1]?.content);

watch(
  () => [visibleMessages.value.length, props.messages[props.messages.length - 1]?.content, props.streaming] as const,
  () => {
    if (visibleMessages.value.length === 0) return;

    const lastMsg = props.messages[props.messages.length - 1];
    const contentChanged = lastMsg?.content !== prevContentRef.value;
    const lenChanged = visibleMessages.value.length !== prevLenRef.value;

    prevLenRef.value = visibleMessages.value.length;
    prevContentRef.value = lastMsg?.content;

    if (!lenChanged && !contentChanged) return;
    if (!props.autoScroll && !props.streaming) return;

    const raf = requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        virtualizer.scrollToIndex(visibleMessages.value.length - 1, { align: "end" });
      });
    });
    return () => cancelAnimationFrame(raf);
  }
);

// Trigger initial scroll to bottom on mount
onMounted(() => {
  if (visibleMessages.value.length > 1) {
    requestAnimationFrame(() => {
      virtualizer.scrollToIndex(visibleMessages.value.length - 1, { align: "end" });
    });
  }
});
</script>

<style scoped>
.message-list-container {
  @apply flex-1 relative;
}

.virtual-list {
  @apply relative w-full;
}

.virtual-row {
  @apply absolute left-0 right-0;
}
</style>
